// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CPDI.EdiFabric.Utilities.Entities;

public partial class EdiPartnerAlias
{
    public int Id { get; set; }

    public string RawId { get; set; }

    public string PartnerKey { get; set; }

    public bool IsSender { get; set; }

    public bool IsReceiver { get; set; }
}