// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CPDI.EdiFabric.Utilities.Entities;

public partial class EdiTemplateMapping
{
    public int Id { get; set; }

    public string PartnerKey { get; set; }

    public string VersionNorm { get; set; }

    public string St01 { get; set; }

    public string TypeFullName { get; set; }

    public string AssemblyName { get; set; }

    public string AssemblyPath { get; set; }

    public bool IsEnabled { get; set; }

    public bool IsStrict { get; set; }

    public int Priority { get; set; }

    public DateTime? EffectiveFromUtc { get; set; }

    public DateTime? EffectiveToUtc { get; set; }
}