namespace EdiFabric.Templates.X12003040
{
    using Microsoft.EntityFrameworkCore;
    using System.Linq;
    
    
    public class X12Context : DbContext
    {
        
        public DbSet<AAA> AAA { get; set; }
        public DbSet<ACK> ACK { get; set; }
        public DbSet<ACS> ACS { get; set; }
        public DbSet<ACT> ACT { get; set; }
        public DbSet<AD1> AD1 { get; set; }
        public DbSet<ADJ> ADJ { get; set; }
        public DbSet<ADX> ADX { get; set; }
        public DbSet<AIN> AIN { get; set; }
        public DbSet<AK1> AK1 { get; set; }
        public DbSet<AK2> AK2 { get; set; }
        public DbSet<AK3> AK3 { get; set; }
        public DbSet<AK4> AK4 { get; set; }
        public DbSet<AK5> AK5 { get; set; }
        public DbSet<AK9> AK9 { get; set; }
        public DbSet<AM1> AM1 { get; set; }
        public DbSet<AMT> AMT { get; set; }
        public DbSet<ARS> ARS { get; set; }
        public DbSet<ASI> ASI { get; set; }
        public DbSet<ASM> ASM { get; set; }
        public DbSet<AT> AT { get; set; }
        public DbSet<ATH> ATH { get; set; }
        public DbSet<AVA> AVA { get; set; }
        public DbSet<B1> B1 { get; set; }
        public DbSet<B10> B10 { get; set; }
        public DbSet<B11> B11 { get; set; }
        public DbSet<B12> B12 { get; set; }
        public DbSet<B2> B2 { get; set; }
        public DbSet<B2A> B2A { get; set; }
        public DbSet<B3> B3 { get; set; }
        public DbSet<B3A> B3A { get; set; }
        public DbSet<B3B> B3B { get; set; }
        public DbSet<B4> B4 { get; set; }
        public DbSet<BA1> BA1 { get; set; }
        public DbSet<BA2> BA2 { get; set; }
        public DbSet<BAA> BAA { get; set; }
        public DbSet<BAK> BAK { get; set; }
        public DbSet<BAL> BAL { get; set; }
        public DbSet<BAT> BAT { get; set; }
        public DbSet<BAU> BAU { get; set; }
        public DbSet<BAX> BAX { get; set; }
        public DbSet<BC> BC { get; set; }
        public DbSet<BCA> BCA { get; set; }
        public DbSet<BCD> BCD { get; set; }
        public DbSet<BCH> BCH { get; set; }
        public DbSet<BCI> BCI { get; set; }
        public DbSet<BCM> BCM { get; set; }
        public DbSet<BCO> BCO { get; set; }
        public DbSet<BCP> BCP { get; set; }
        public DbSet<BCQ> BCQ { get; set; }
        public DbSet<BCS> BCS { get; set; }
        public DbSet<BCT> BCT { get; set; }
        public DbSet<BEG> BEG { get; set; }
        public DbSet<BEN> BEN { get; set; }
        public DbSet<BFR> BFR { get; set; }
        public DbSet<BFS> BFS { get; set; }
        public DbSet<BGF> BGF { get; set; }
        public DbSet<BGN> BGN { get; set; }
        public DbSet<BHT> BHT { get; set; }
        public DbSet<BIA> BIA { get; set; }
        public DbSet<BIG> BIG { get; set; }
        public DbSet<BIN> BIN { get; set; }
        public DbSet<BIX> BIX { get; set; }
        public DbSet<BL> BL { get; set; }
        public DbSet<BLI> BLI { get; set; }
        public DbSet<BLR> BLR { get; set; }
        public DbSet<BLS> BLS { get; set; }
        public DbSet<BMG> BMG { get; set; }
        public DbSet<BMM> BMM { get; set; }
        public DbSet<BMS> BMS { get; set; }
        public DbSet<BNR> BNR { get; set; }
        public DbSet<BNX> BNX { get; set; }
        public DbSet<BOS> BOS { get; set; }
        public DbSet<BOX> BOX { get; set; }
        public DbSet<BPA> BPA { get; set; }
        public DbSet<BPP> BPP { get; set; }
        public DbSet<BPR> BPR { get; set; }
        public DbSet<BPS> BPS { get; set; }
        public DbSet<BPT> BPT { get; set; }
        public DbSet<BQR> BQR { get; set; }
        public DbSet<BQT> BQT { get; set; }
        public DbSet<BR> BR { get; set; }
        public DbSet<BRA> BRA { get; set; }
        public DbSet<BRC> BRC { get; set; }
        public DbSet<BSC> BSC { get; set; }
        public DbSet<BSD> BSD { get; set; }
        public DbSet<BSI> BSI { get; set; }
        public DbSet<BSN> BSN { get; set; }
        public DbSet<BSR> BSR { get; set; }
        public DbSet<BSS> BSS { get; set; }
        public DbSet<BT1> BT1 { get; set; }
        public DbSet<BTA> BTA { get; set; }
        public DbSet<BTI> BTI { get; set; }
        public DbSet<BTP> BTP { get; set; }
        public DbSet<BTR> BTR { get; set; }
        public DbSet<BTS> BTS { get; set; }
        public DbSet<BUY> BUY { get; set; }
        public DbSet<BVA> BVA { get; set; }
        public DbSet<BVB> BVB { get; set; }
        public DbSet<BW> BW { get; set; }
        public DbSet<BX> BX { get; set; }
        public DbSet<C2> C2 { get; set; }
        public DbSet<C3> C3 { get; set; }
        public DbSet<C4> C4 { get; set; }
        public DbSet<C8> C8 { get; set; }
        public DbSet<C8C> C8C { get; set; }
        public DbSet<CA1> CA1 { get; set; }
        public DbSet<CAD> CAD { get; set; }
        public DbSet<CAI> CAI { get; set; }
        public DbSet<CAL> CAL { get; set; }
        public DbSet<CAS> CAS { get; set; }
        public DbSet<CB1> CB1 { get; set; }
        public DbSet<CBS> CBS { get; set; }
        public DbSet<CD> CD { get; set; }
        public DbSet<CD1> CD1 { get; set; }
        public DbSet<CD2> CD2 { get; set; }
        public DbSet<CDA> CDA { get; set; }
        public DbSet<CDD> CDD { get; set; }
        public DbSet<CFT> CFT { get; set; }
        public DbSet<CHR> CHR { get; set; }
        public DbSet<CI> CI { get; set; }
        public DbSet<CIC> CIC { get; set; }
        public DbSet<CID> CID { get; set; }
        public DbSet<CIV> CIV { get; set; }
        public DbSet<CL> CL { get; set; }
        public DbSet<CL1> CL1 { get; set; }
        public DbSet<CLD> CLD { get; set; }
        public DbSet<CLI> CLI { get; set; }
        public DbSet<CLM> CLM { get; set; }
        public DbSet<CLP> CLP { get; set; }
        public DbSet<CM> CM { get; set; }
        public DbSet<CMA> CMA { get; set; }
        public DbSet<CN1> CN1 { get; set; }
        public DbSet<COB> COB { get; set; }
        public DbSet<CON> CON { get; set; }
        public DbSet<CPR> CPR { get; set; }
        public DbSet<CR1> CR1 { get; set; }
        public DbSet<CR2> CR2 { get; set; }
        public DbSet<CR3> CR3 { get; set; }
        public DbSet<CR4> CR4 { get; set; }
        public DbSet<CR5> CR5 { get; set; }
        public DbSet<CR8> CR8 { get; set; }
        public DbSet<CRC> CRC { get; set; }
        public DbSet<CRI> CRI { get; set; }
        public DbSet<CRO> CRO { get; set; }
        public DbSet<CRS> CRS { get; set; }
        public DbSet<CRT> CRT { get; set; }
        public DbSet<CS> CS { get; set; }
        public DbSet<CSB> CSB { get; set; }
        public DbSet<CSF> CSF { get; set; }
        public DbSet<CSH> CSH { get; set; }
        public DbSet<CSI> CSI { get; set; }
        public DbSet<CSM> CSM { get; set; }
        public DbSet<CSS> CSS { get; set; }
        public DbSet<CST> CST { get; set; }
        public DbSet<CSU> CSU { get; set; }
        public DbSet<CTB> CTB { get; set; }
        public DbSet<CTC> CTC { get; set; }
        public DbSet<CTP> CTP { get; set; }
        public DbSet<CTT> CTT { get; set; }
        public DbSet<CUR> CUR { get; set; }
        public DbSet<CV> CV { get; set; }
        public DbSet<CYC> CYC { get; set; }
        public DbSet<D9> D9 { get; set; }
        public DbSet<DAD> DAD { get; set; }
        public DbSet<DAI> DAI { get; set; }
        public DbSet<DAM> DAM { get; set; }
        public DbSet<DB> DB { get; set; }
        public DbSet<DD> DD { get; set; }
        public DbSet<DDI> DDI { get; set; }
        public DbSet<DEF> DEF { get; set; }
        public DbSet<DEG> DEG { get; set; }
        public DbSet<DEP> DEP { get; set; }
        public DbSet<DFI> DFI { get; set; }
        public DbSet<DH> DH { get; set; }
        public DbSet<DIS> DIS { get; set; }
        public DbSet<DK> DK { get; set; }
        public DbSet<DLV> DLV { get; set; }
        public DbSet<DM> DM { get; set; }
        public DbSet<DMA> DMA { get; set; }
        public DbSet<DMG> DMG { get; set; }
        public DbSet<DMI> DMI { get; set; }
        public DbSet<DN> DN { get; set; }
        public DbSet<DN1> DN1 { get; set; }
        public DbSet<DN2> DN2 { get; set; }
        public DbSet<DOS> DOS { get; set; }
        public DbSet<DSB> DSB { get; set; }
        public DbSet<DTM> DTM { get; set; }
        public DbSet<DTP> DTP { get; set; }
        public DbSet<DVI> DVI { get; set; }
        public DbSet<E01> E01 { get; set; }
        public DbSet<E03> E03 { get; set; }
        public DbSet<E1> E1 { get; set; }
        public DbSet<E10> E10 { get; set; }
        public DbSet<E13> E13 { get; set; }
        public DbSet<E20> E20 { get; set; }
        public DbSet<E22> E22 { get; set; }
        public DbSet<E24> E24 { get; set; }
        public DbSet<E26> E26 { get; set; }
        public DbSet<E30> E30 { get; set; }
        public DbSet<E34> E34 { get; set; }
        public DbSet<E4> E4 { get; set; }
        public DbSet<E40> E40 { get; set; }
        public DbSet<E5> E5 { get; set; }
        public DbSet<E6> E6 { get; set; }
        public DbSet<E8> E8 { get; set; }
        public DbSet<EA> EA { get; set; }
        public DbSet<EB> EB { get; set; }
        public DbSet<EC> EC { get; set; }
        public DbSet<ED> ED { get; set; }
        public DbSet<EFI> EFI { get; set; }
        public DbSet<EM> EM { get; set; }
        public DbSet<EMP> EMP { get; set; }
        public DbSet<EMS> EMS { get; set; }
        public DbSet<EMT> EMT { get; set; }
        public DbSet<ENE> ENE { get; set; }
        public DbSet<ENR> ENR { get; set; }
        public DbSet<ENT> ENT { get; set; }
        public DbSet<EQ> EQ { get; set; }
        public DbSet<ERI> ERI { get; set; }
        public DbSet<ERP> ERP { get; set; }
        public DbSet<ESI> ESI { get; set; }
        public DbSet<ETD> ETD { get; set; }
        public DbSet<F01> F01 { get; set; }
        public DbSet<F02> F02 { get; set; }
        public DbSet<F04> F04 { get; set; }
        public DbSet<F05> F05 { get; set; }
        public DbSet<F07> F07 { get; set; }
        public DbSet<F09> F09 { get; set; }
        public DbSet<F10> F10 { get; set; }
        public DbSet<F11> F11 { get; set; }
        public DbSet<F12> F12 { get; set; }
        public DbSet<F13> F13 { get; set; }
        public DbSet<F14> F14 { get; set; }
        public DbSet<F6X> F6X { get; set; }
        public DbSet<F9> F9 { get; set; }
        public DbSet<FAA> FAA { get; set; }
        public DbSet<FAC> FAC { get; set; }
        public DbSet<FBB> FBB { get; set; }
        public DbSet<FC> FC { get; set; }
        public DbSet<FCL> FCL { get; set; }
        public DbSet<FGS> FGS { get; set; }
        public DbSet<FIR> FIR { get; set; }
        public DbSet<FIS> FIS { get; set; }
        public DbSet<FK> FK { get; set; }
        public DbSet<FNA> FNA { get; set; }
        public DbSet<FOB> FOB { get; set; }
        public DbSet<FOS> FOS { get; set; }
        public DbSet<FPT> FPT { get; set; }
        public DbSet<FSA> FSA { get; set; }
        public DbSet<FST> FST { get; set; }
        public DbSet<G01> G01 { get; set; }
        public DbSet<G05> G05 { get; set; }
        public DbSet<G07> G07 { get; set; }
        public DbSet<G08> G08 { get; set; }
        public DbSet<G1> G1 { get; set; }
        public DbSet<G17> G17 { get; set; }
        public DbSet<G19> G19 { get; set; }
        public DbSet<G2> G2 { get; set; }
        public DbSet<G20> G20 { get; set; }
        public DbSet<G21> G21 { get; set; }
        public DbSet<G22> G22 { get; set; }
        public DbSet<G23> G23 { get; set; }
        public DbSet<G24> G24 { get; set; }
        public DbSet<G25> G25 { get; set; }
        public DbSet<G26> G26 { get; set; }
        public DbSet<G27> G27 { get; set; }
        public DbSet<G28> G28 { get; set; }
        public DbSet<G3> G3 { get; set; }
        public DbSet<G31> G31 { get; set; }
        public DbSet<G33> G33 { get; set; }
        public DbSet<G36> G36 { get; set; }
        public DbSet<G39> G39 { get; set; }
        public DbSet<G4> G4 { get; set; }
        public DbSet<G40> G40 { get; set; }
        public DbSet<G42> G42 { get; set; }
        public DbSet<G43> G43 { get; set; }
        public DbSet<G45> G45 { get; set; }
        public DbSet<G46> G46 { get; set; }
        public DbSet<G47> G47 { get; set; }
        public DbSet<G48> G48 { get; set; }
        public DbSet<G49> G49 { get; set; }
        public DbSet<G5> G5 { get; set; }
        public DbSet<G50> G50 { get; set; }
        public DbSet<G51> G51 { get; set; }
        public DbSet<G53> G53 { get; set; }
        public DbSet<G54> G54 { get; set; }
        public DbSet<G55> G55 { get; set; }
        public DbSet<G61> G61 { get; set; }
        public DbSet<G62> G62 { get; set; }
        public DbSet<G63> G63 { get; set; }
        public DbSet<G66> G66 { get; set; }
        public DbSet<G68> G68 { get; set; }
        public DbSet<G69> G69 { get; set; }
        public DbSet<G70> G70 { get; set; }
        public DbSet<G72> G72 { get; set; }
        public DbSet<G73> G73 { get; set; }
        public DbSet<G76> G76 { get; set; }
        public DbSet<G82> G82 { get; set; }
        public DbSet<G83> G83 { get; set; }
        public DbSet<G84> G84 { get; set; }
        public DbSet<G85> G85 { get; set; }
        public DbSet<G86> G86 { get; set; }
        public DbSet<G87> G87 { get; set; }
        public DbSet<G88> G88 { get; set; }
        public DbSet<G89> G89 { get; set; }
        public DbSet<G91> G91 { get; set; }
        public DbSet<G92> G92 { get; set; }
        public DbSet<G93> G93 { get; set; }
        public DbSet<G94> G94 { get; set; }
        public DbSet<G95> G95 { get; set; }
        public DbSet<GA> GA { get; set; }
        public DbSet<GF> GF { get; set; }
        public DbSet<GH> GH { get; set; }
        public DbSet<GOV> GOV { get; set; }
        public DbSet<GR> GR { get; set; }
        public DbSet<GR5> GR5 { get; set; }
        public DbSet<GRI> GRI { get; set; }
        public DbSet<GY> GY { get; set; }
        public DbSet<H1> H1 { get; set; }
        public DbSet<H2> H2 { get; set; }
        public DbSet<H3> H3 { get; set; }
        public DbSet<H5> H5 { get; set; }
        public DbSet<H6> H6 { get; set; }
        public DbSet<HC> HC { get; set; }
        public DbSet<HCP> HCP { get; set; }
        public DbSet<HD> HD { get; set; }
        public DbSet<HL> HL { get; set; }
        public DbSet<HLH> HLH { get; set; }
        public DbSet<HS> HS { get; set; }
        public DbSet<IC> IC { get; set; }
        public DbSet<ICH> ICH { get; set; }
        public DbSet<ICM> ICM { get; set; }
        public DbSet<ID> ID { get; set; }
        public DbSet<ID1> ID1 { get; set; }
        public DbSet<ID2> ID2 { get; set; }
        public DbSet<ID3> ID3 { get; set; }
        public DbSet<IDB> IDB { get; set; }
        public DbSet<IDC> IDC { get; set; }
        public DbSet<III> III { get; set; }
        public DbSet<IM> IM { get; set; }
        public DbSet<IMA> IMA { get; set; }
        public DbSet<IMM> IMM { get; set; }
        public DbSet<IMP> IMP { get; set; }
        public DbSet<IN1> IN1 { get; set; }
        public DbSet<IN2> IN2 { get; set; }
        public DbSet<INC> INC { get; set; }
        public DbSet<IND> IND { get; set; }
        public DbSet<INJ> INJ { get; set; }
        public DbSet<INS> INS { get; set; }
        public DbSet<INT> INT { get; set; }
        public DbSet<INV> INV { get; set; }
        public DbSet<IS1> IS1 { get; set; }
        public DbSet<IS2> IS2 { get; set; }
        public DbSet<ISR> ISR { get; set; }
        public DbSet<ISS> ISS { get; set; }
        public DbSet<IT1> IT1 { get; set; }
        public DbSet<IT3> IT3 { get; set; }
        public DbSet<IT8> IT8 { get; set; }
        public DbSet<ITA> ITA { get; set; }
        public DbSet<ITD> ITD { get; set; }
        public DbSet<JID> JID { get; set; }
        public DbSet<JIL> JIL { get; set; }
        public DbSet<JIT> JIT { get; set; }
        public DbSet<JL> JL { get; set; }
        public DbSet<K1> K1 { get; set; }
        public DbSet<K2> K2 { get; set; }
        public DbSet<K3> K3 { get; set; }
        public DbSet<L0> L0 { get; set; }
        public DbSet<L1> L1 { get; set; }
        public DbSet<L10> L10 { get; set; }
        public DbSet<L11> L11 { get; set; }
        public DbSet<L12> L12 { get; set; }
        public DbSet<L13> L13 { get; set; }
        public DbSet<L1A> L1A { get; set; }
        public DbSet<L3> L3 { get; set; }
        public DbSet<L4> L4 { get; set; }
        public DbSet<L5> L5 { get; set; }
        public DbSet<L7> L7 { get; set; }
        public DbSet<L7A> L7A { get; set; }
        public DbSet<L8> L8 { get; set; }
        public DbSet<L9> L9 { get; set; }
        public DbSet<LAD> LAD { get; set; }
        public DbSet<LC> LC { get; set; }
        public DbSet<LCD> LCD { get; set; }
        public DbSet<LDT> LDT { get; set; }
        public DbSet<LE> LE { get; set; }
        public DbSet<LEP> LEP { get; set; }
        public DbSet<LEQ> LEQ { get; set; }
        public DbSet<LFH> LFH { get; set; }
        public DbSet<LH> LH { get; set; }
        public DbSet<LH1> LH1 { get; set; }
        public DbSet<LH2> LH2 { get; set; }
        public DbSet<LH3> LH3 { get; set; }
        public DbSet<LH4> LH4 { get; set; }
        public DbSet<LH6> LH6 { get; set; }
        public DbSet<LHE> LHE { get; set; }
        public DbSet<LHR> LHR { get; set; }
        public DbSet<LHT> LHT { get; set; }
        public DbSet<LID> LID { get; set; }
        public DbSet<LIE> LIE { get; set; }
        public DbSet<LIN> LIN { get; set; }
        public DbSet<LM> LM { get; set; }
        public DbSet<LN> LN { get; set; }
        public DbSet<LN1> LN1 { get; set; }
        public DbSet<LOC> LOC { get; set; }
        public DbSet<LQ> LQ { get; set; }
        public DbSet<LRQ> LRQ { get; set; }
        public DbSet<LS> LS { get; set; }
        public DbSet<LS1> LS1 { get; set; }
        public DbSet<LTR> LTR { get; set; }
        public DbSet<LV> LV { get; set; }
        public DbSet<LX> LX { get; set; }
        public DbSet<M0> M0 { get; set; }
        public DbSet<M1> M1 { get; set; }
        public DbSet<M10> M10 { get; set; }
        public DbSet<M11> M11 { get; set; }
        public DbSet<M12> M12 { get; set; }
        public DbSet<M13> M13 { get; set; }
        public DbSet<M14> M14 { get; set; }
        public DbSet<M15> M15 { get; set; }
        public DbSet<M2> M2 { get; set; }
        public DbSet<M20> M20 { get; set; }
        public DbSet<M21> M21 { get; set; }
        public DbSet<M3> M3 { get; set; }
        public DbSet<M7> M7 { get; set; }
        public DbSet<MAN> MAN { get; set; }
        public DbSet<MBL> MBL { get; set; }
        public DbSet<MC> MC { get; set; }
        public DbSet<MCD> MCD { get; set; }
        public DbSet<MCT> MCT { get; set; }
        public DbSet<MEA> MEA { get; set; }
        public DbSet<MI> MI { get; set; }
        public DbSet<MIA> MIA { get; set; }
        public DbSet<MII> MII { get; set; }
        public DbSet<MIL> MIL { get; set; }
        public DbSet<MIN> MIN { get; set; }
        public DbSet<MIR> MIR { get; set; }
        public DbSet<MIS> MIS { get; set; }
        public DbSet<MIT> MIT { get; set; }
        public DbSet<MOA> MOA { get; set; }
        public DbSet<MRC> MRC { get; set; }
        public DbSet<MS> MS { get; set; }
        public DbSet<MSG> MSG { get; set; }
        public DbSet<MSS> MSS { get; set; }
        public DbSet<N1> N1 { get; set; }
        public DbSet<N10> N10 { get; set; }
        public DbSet<N11> N11 { get; set; }
        public DbSet<N12> N12 { get; set; }
        public DbSet<N2> N2 { get; set; }
        public DbSet<N3> N3 { get; set; }
        public DbSet<N4> N4 { get; set; }
        public DbSet<N5> N5 { get; set; }
        public DbSet<N7> N7 { get; set; }
        public DbSet<N7A> N7A { get; set; }
        public DbSet<N7B> N7B { get; set; }
        public DbSet<N8> N8 { get; set; }
        public DbSet<N8A> N8A { get; set; }
        public DbSet<N9> N9 { get; set; }
        public DbSet<NA> NA { get; set; }
        public DbSet<NCA> NCA { get; set; }
        public DbSet<NCD> NCD { get; set; }
        public DbSet<NM1> NM1 { get; set; }
        public DbSet<NTE> NTE { get; set; }
        public DbSet<NX1> NX1 { get; set; }
        public DbSet<NX2> NX2 { get; set; }
        public DbSet<OI> OI { get; set; }
        public DbSet<OP> OP { get; set; }
        public DbSet<OPS> OPS { get; set; }
        public DbSet<OPX> OPX { get; set; }
        public DbSet<OQS> OQS { get; set; }
        public DbSet<OTI> OTI { get; set; }
        public DbSet<P1> P1 { get; set; }
        public DbSet<P2> P2 { get; set; }
        public DbSet<P4> P4 { get; set; }
        public DbSet<P5> P5 { get; set; }
        public DbSet<PAD> PAD { get; set; }
        public DbSet<PAI> PAI { get; set; }
        public DbSet<PAL> PAL { get; set; }
        public DbSet<PAM> PAM { get; set; }
        public DbSet<PAS> PAS { get; set; }
        public DbSet<PAT> PAT { get; set; }
        public DbSet<PAY> PAY { get; set; }
        public DbSet<PBI> PBI { get; set; }
        public DbSet<PC> PC { get; set; }
        public DbSet<PCL> PCL { get; set; }
        public DbSet<PCR> PCR { get; set; }
        public DbSet<PCS> PCS { get; set; }
        public DbSet<PCT> PCT { get; set; }
        public DbSet<PD> PD { get; set; }
        public DbSet<PDD> PDD { get; set; }
        public DbSet<PEN> PEN { get; set; }
        public DbSet<PER> PER { get; set; }
        public DbSet<PEX> PEX { get; set; }
        public DbSet<PI> PI { get; set; }
        public DbSet<PID> PID { get; set; }
        public DbSet<PIN> PIN { get; set; }
        public DbSet<PKD> PKD { get; set; }
        public DbSet<PKG> PKG { get; set; }
        public DbSet<PKL> PKL { get; set; }
        public DbSet<PL> PL { get; set; }
        public DbSet<PLA> PLA { get; set; }
        public DbSet<PLB> PLB { get; set; }
        public DbSet<PLI> PLI { get; set; }
        public DbSet<PM> PM { get; set; }
        public DbSet<PO1> PO1 { get; set; }
        public DbSet<PO3> PO3 { get; set; }
        public DbSet<PO4> PO4 { get; set; }
        public DbSet<POC> POC { get; set; }
        public DbSet<POD> POD { get; set; }
        public DbSet<PPL> PPL { get; set; }
        public DbSet<PPY> PPY { get; set; }
        public DbSet<PR> PR { get; set; }
        public DbSet<PR1> PR1 { get; set; }
        public DbSet<PR2> PR2 { get; set; }
        public DbSet<PRD> PRD { get; set; }
        public DbSet<PRF> PRF { get; set; }
        public DbSet<PRI> PRI { get; set; }
        public DbSet<PRJ> PRJ { get; set; }
        public DbSet<PRO> PRO { get; set; }
        public DbSet<PRR> PRR { get; set; }
        public DbSet<PRS> PRS { get; set; }
        public DbSet<PRT> PRT { get; set; }
        public DbSet<PRV> PRV { get; set; }
        public DbSet<PS> PS { get; set; }
        public DbSet<PS1> PS1 { get; set; }
        public DbSet<PSA> PSA { get; set; }
        public DbSet<PSC> PSC { get; set; }
        public DbSet<PSD> PSD { get; set; }
        public DbSet<PT> PT { get; set; }
        public DbSet<PTD> PTD { get; set; }
        public DbSet<PWK> PWK { get; set; }
        public DbSet<Q2> Q2 { get; set; }
        public DbSet<Q3> Q3 { get; set; }
        public DbSet<Q5> Q5 { get; set; }
        public DbSet<Q6> Q6 { get; set; }
        public DbSet<Q7> Q7 { get; set; }
        public DbSet<Q8> Q8 { get; set; }
        public DbSet<QTY> QTY { get; set; }
        public DbSet<R1> R1 { get; set; }
        public DbSet<R2> R2 { get; set; }
        public DbSet<R2A> R2A { get; set; }
        public DbSet<R2B> R2B { get; set; }
        public DbSet<R2C> R2C { get; set; }
        public DbSet<R2D> R2D { get; set; }
        public DbSet<R3> R3 { get; set; }
        public DbSet<R4> R4 { get; set; }
        public DbSet<R9> R9 { get; set; }
        public DbSet<RA> RA { get; set; }
        public DbSet<RAP> RAP { get; set; }
        public DbSet<RAT> RAT { get; set; }
        public DbSet<RB> RB { get; set; }
        public DbSet<RC> RC { get; set; }
        public DbSet<RCD> RCD { get; set; }
        public DbSet<RDR> RDR { get; set; }
        public DbSet<RDT> RDT { get; set; }
        public DbSet<RE> RE { get; set; }
        public DbSet<REA> REA { get; set; }
        public DbSet<REC> REC { get; set; }
        public DbSet<REF> REF { get; set; }
        public DbSet<REL> REL { get; set; }
        public DbSet<REN> REN { get; set; }
        public DbSet<REP> REP { get; set; }
        public DbSet<REQ> REQ { get; set; }
        public DbSet<RES> RES { get; set; }
        public DbSet<RH> RH { get; set; }
        public DbSet<RIC> RIC { get; set; }
        public DbSet<RLD> RLD { get; set; }
        public DbSet<RMR> RMR { get; set; }
        public DbSet<RMT> RMT { get; set; }
        public DbSet<RP> RP { get; set; }
        public DbSet<RPA> RPA { get; set; }
        public DbSet<RRA> RRA { get; set; }
        public DbSet<RST> RST { get; set; }
        public DbSet<RT> RT { get; set; }
        public DbSet<RT1> RT1 { get; set; }
        public DbSet<RTE> RTE { get; set; }
        public DbSet<RTS> RTS { get; set; }
        public DbSet<RU1> RU1 { get; set; }
        public DbSet<RU2> RU2 { get; set; }
        public DbSet<RU3> RU3 { get; set; }
        public DbSet<S1> S1 { get; set; }
        public DbSet<S2> S2 { get; set; }
        public DbSet<S5> S5 { get; set; }
        public DbSet<S9> S9 { get; set; }
        public DbSet<SA> SA { get; set; }
        public DbSet<SAC> SAC { get; set; }
        public DbSet<SAL> SAL { get; set; }
        public DbSet<SB> SB { get; set; }
        public DbSet<SBR> SBR { get; set; }
        public DbSet<SBT> SBT { get; set; }
        public DbSet<SC> SC { get; set; }
        public DbSet<SCH> SCH { get; set; }
        public DbSet<SCL> SCL { get; set; }
        public DbSet<SCO> SCO { get; set; }
        public DbSet<SCT> SCT { get; set; }
        public DbSet<SD1> SD1 { get; set; }
        public DbSet<SDP> SDP { get; set; }
        public DbSet<SDQ> SDQ { get; set; }
        public DbSet<SER> SER { get; set; }
        public DbSet<SES> SES { get; set; }
        public DbSet<SFC> SFC { get; set; }
        public DbSet<SG> SG { get; set; }
        public DbSet<SHD> SHD { get; set; }
        public DbSet<SHP> SHP { get; set; }
        public DbSet<SI> SI { get; set; }
        public DbSet<SL1> SL1 { get; set; }
        public DbSet<SLI> SLI { get; set; }
        public DbSet<SLN> SLN { get; set; }
        public DbSet<SMA> SMA { get; set; }
        public DbSet<SMB> SMB { get; set; }
        public DbSet<SMO> SMO { get; set; }
        public DbSet<SMR> SMR { get; set; }
        public DbSet<SMS> SMS { get; set; }
        public DbSet<SN1> SN1 { get; set; }
        public DbSet<SOM> SOM { get; set; }
        public DbSet<SP> SP { get; set; }
        public DbSet<SPI> SPI { get; set; }
        public DbSet<SPK> SPK { get; set; }
        public DbSet<SPR> SPR { get; set; }
        public DbSet<SPS> SPS { get; set; }
        public DbSet<SR> SR { get; set; }
        public DbSet<SRA> SRA { get; set; }
        public DbSet<SRC> SRC { get; set; }
        public DbSet<SRD> SRD { get; set; }
        public DbSet<SRE> SRE { get; set; }
        public DbSet<SRM> SRM { get; set; }
        public DbSet<SRT> SRT { get; set; }
        public DbSet<SS> SS { get; set; }
        public DbSet<SSE> SSE { get; set; }
        public DbSet<SSS> SSS { get; set; }
        public DbSet<SST> SST { get; set; }
        public DbSet<STA> STA { get; set; }
        public DbSet<STC> STC { get; set; }
        public DbSet<SUM> SUM { get; set; }
        public DbSet<SUP> SUP { get; set; }
        public DbSet<SV> SV { get; set; }
        public DbSet<SV1> SV1 { get; set; }
        public DbSet<SV2> SV2 { get; set; }
        public DbSet<SV3> SV3 { get; set; }
        public DbSet<SV4> SV4 { get; set; }
        public DbSet<SV5> SV5 { get; set; }
        public DbSet<SV6> SV6 { get; set; }
        public DbSet<SV7> SV7 { get; set; }
        public DbSet<SVC> SVC { get; set; }
        public DbSet<SW> SW { get; set; }
        public DbSet<T1> T1 { get; set; }
        public DbSet<T2> T2 { get; set; }
        public DbSet<T3> T3 { get; set; }
        public DbSet<T6> T6 { get; set; }
        public DbSet<T8> T8 { get; set; }
        public DbSet<TAX> TAX { get; set; }
        public DbSet<TBA> TBA { get; set; }
        public DbSet<TC2> TC2 { get; set; }
        public DbSet<TCD> TCD { get; set; }
        public DbSet<TD1> TD1 { get; set; }
        public DbSet<TD3> TD3 { get; set; }
        public DbSet<TD4> TD4 { get; set; }
        public DbSet<TD5> TD5 { get; set; }
        public DbSet<TDS> TDS { get; set; }
        public DbSet<TED> TED { get; set; }
        public DbSet<TF> TF { get; set; }
        public DbSet<TFA> TFA { get; set; }
        public DbSet<TFD> TFD { get; set; }
        public DbSet<TFM> TFM { get; set; }
        public DbSet<TFR> TFR { get; set; }
        public DbSet<TFS> TFS { get; set; }
        public DbSet<THE> THE { get; set; }
        public DbSet<TI> TI { get; set; }
        public DbSet<TIA> TIA { get; set; }
        public DbSet<TID> TID { get; set; }
        public DbSet<TMD> TMD { get; set; }
        public DbSet<TPD> TPD { get; set; }
        public DbSet<TRF> TRF { get; set; }
        public DbSet<TRN> TRN { get; set; }
        public DbSet<TS> TS { get; set; }
        public DbSet<TS2> TS2 { get; set; }
        public DbSet<TS3> TS3 { get; set; }
        public DbSet<TSP> TSP { get; set; }
        public DbSet<TST> TST { get; set; }
        public DbSet<TT> TT { get; set; }
        public DbSet<TUD> TUD { get; set; }
        public DbSet<TXI> TXI { get; set; }
        public DbSet<TXN> TXN { get; set; }
        public DbSet<TXP> TXP { get; set; }
        public DbSet<UIT> UIT { get; set; }
        public DbSet<UR> UR { get; set; }
        public DbSet<USD> USD { get; set; }
        public DbSet<V1> V1 { get; set; }
        public DbSet<V2> V2 { get; set; }
        public DbSet<V3> V3 { get; set; }
        public DbSet<V4> V4 { get; set; }
        public DbSet<V5> V5 { get; set; }
        public DbSet<V9> V9 { get; set; }
        public DbSet<VAD> VAD { get; set; }
        public DbSet<VAT> VAT { get; set; }
        public DbSet<VC> VC { get; set; }
        public DbSet<VEH> VEH { get; set; }
        public DbSet<VID> VID { get; set; }
        public DbSet<VR> VR { get; set; }
        public DbSet<VRC> VRC { get; set; }
        public DbSet<W01> W01 { get; set; }
        public DbSet<W03> W03 { get; set; }
        public DbSet<W04> W04 { get; set; }
        public DbSet<W05> W05 { get; set; }
        public DbSet<W06> W06 { get; set; }
        public DbSet<W07> W07 { get; set; }
        public DbSet<W08> W08 { get; set; }
        public DbSet<W09> W09 { get; set; }
        public DbSet<W1> W1 { get; set; }
        public DbSet<W10> W10 { get; set; }
        public DbSet<W12> W12 { get; set; }
        public DbSet<W13> W13 { get; set; }
        public DbSet<W14> W14 { get; set; }
        public DbSet<W15> W15 { get; set; }
        public DbSet<W17> W17 { get; set; }
        public DbSet<W18> W18 { get; set; }
        public DbSet<W19> W19 { get; set; }
        public DbSet<W2> W2 { get; set; }
        public DbSet<W20> W20 { get; set; }
        public DbSet<W27> W27 { get; set; }
        public DbSet<W28> W28 { get; set; }
        public DbSet<W2A> W2A { get; set; }
        public DbSet<W3> W3 { get; set; }
        public DbSet<W4> W4 { get; set; }
        public DbSet<W5> W5 { get; set; }
        public DbSet<W6> W6 { get; set; }
        public DbSet<W66> W66 { get; set; }
        public DbSet<W76> W76 { get; set; }
        public DbSet<WGP> WGP { get; set; }
        public DbSet<WS> WS { get; set; }
        public DbSet<X01> X01 { get; set; }
        public DbSet<X02> X02 { get; set; }
        public DbSet<X1> X1 { get; set; }
        public DbSet<X2> X2 { get; set; }
        public DbSet<X4> X4 { get; set; }
        public DbSet<X7> X7 { get; set; }
        public DbSet<XH> XH { get; set; }
        public DbSet<XPO> XPO { get; set; }
        public DbSet<XQ> XQ { get; set; }
        public DbSet<Y1> Y1 { get; set; }
        public DbSet<Y2> Y2 { get; set; }
        public DbSet<Y3> Y3 { get; set; }
        public DbSet<Y4> Y4 { get; set; }
        public DbSet<Y5> Y5 { get; set; }
        public DbSet<Y6> Y6 { get; set; }
        public DbSet<Y7> Y7 { get; set; }
        public DbSet<ZA> ZA { get; set; }
        public DbSet<ZC1> ZC1 { get; set; }
        public DbSet<ZD> ZD { get; set; }
        public DbSet<ZR> ZR { get; set; }
        public DbSet<ZT> ZT { get; set; }
        public DbSet<C001> C001 { get; set; }
        public DbSet<C002> C002 { get; set; }
        public DbSet<C003> C003 { get; set; }
        public DbSet<C004> C004 { get; set; }
        public DbSet<Loop_FOB_104> Loop_FOB_104 { get; set; }
        public DbSet<Loop_L5_104> Loop_L5_104 { get; set; }
        public DbSet<Loop_N1_104> Loop_N1_104 { get; set; }
        public DbSet<TS104> TS104 { get; set; }
        public DbSet<Loop_L1_110> Loop_L1_110 { get; set; }
        public DbSet<Loop_L5_110> Loop_L5_110 { get; set; }
        public DbSet<Loop_LX_110> Loop_LX_110 { get; set; }
        public DbSet<Loop_N1_110> Loop_N1_110 { get; set; }
        public DbSet<Loop_N1_110_2> Loop_N1_110_2 { get; set; }
        public DbSet<TS110> TS110 { get; set; }
        public DbSet<TS125> TS125 { get; set; }
        public DbSet<Loop_BVA_126> Loop_BVA_126 { get; set; }
        public DbSet<Loop_VAD_126> Loop_VAD_126 { get; set; }
        public DbSet<TS126> TS126 { get; set; }
        public DbSet<TS127> TS127 { get; set; }
        public DbSet<TS128> TS128 { get; set; }
        public DbSet<Loop_RT_129> Loop_RT_129 { get; set; }
        public DbSet<TS129> TS129 { get; set; }
        public DbSet<Loop_CRS_130> Loop_CRS_130 { get; set; }
        public DbSet<Loop_DEG_130> Loop_DEG_130 { get; set; }
        public DbSet<Loop_HC_130> Loop_HC_130 { get; set; }
        public DbSet<Loop_IN1_130> Loop_IN1_130 { get; set; }
        public DbSet<Loop_LX_130> Loop_LX_130 { get; set; }
        public DbSet<Loop_N1_130> Loop_N1_130 { get; set; }
        public DbSet<Loop_OP_130> Loop_OP_130 { get; set; }
        public DbSet<Loop_SBT_130> Loop_SBT_130 { get; set; }
        public DbSet<Loop_SES_130> Loop_SES_130 { get; set; }
        public DbSet<Loop_SP_130> Loop_SP_130 { get; set; }
        public DbSet<Loop_SST_130> Loop_SST_130 { get; set; }
        public DbSet<Loop_SUM_130> Loop_SUM_130 { get; set; }
        public DbSet<Loop_TST_130> Loop_TST_130 { get; set; }
        public DbSet<TS130> TS130 { get; set; }
        public DbSet<TS131> TS131 { get; set; }
        public DbSet<Loop_ENT_135> Loop_ENT_135 { get; set; }
        public DbSet<Loop_IN1_135> Loop_IN1_135 { get; set; }
        public DbSet<Loop_LX_135> Loop_LX_135 { get; set; }
        public DbSet<Loop_N1_135> Loop_N1_135 { get; set; }
        public DbSet<Loop_PLI_135> Loop_PLI_135 { get; set; }
        public DbSet<TS135> TS135 { get; set; }
        public DbSet<Loop_AMT_139> Loop_AMT_139 { get; set; }
        public DbSet<Loop_ENT_139> Loop_ENT_139 { get; set; }
        public DbSet<Loop_LM_139> Loop_LM_139 { get; set; }
        public DbSet<TS139> TS139 { get; set; }
        public DbSet<Loop_LIN_140> Loop_LIN_140 { get; set; }
        public DbSet<Loop_LM_140> Loop_LM_140 { get; set; }
        public DbSet<Loop_LX_140> Loop_LX_140 { get; set; }
        public DbSet<Loop_N1_140> Loop_N1_140 { get; set; }
        public DbSet<Loop_N1_140_2> Loop_N1_140_2 { get; set; }
        public DbSet<Loop_N1_140_3> Loop_N1_140_3 { get; set; }
        public DbSet<Loop_PSC_140> Loop_PSC_140 { get; set; }
        public DbSet<Loop_SLN_140> Loop_SLN_140 { get; set; }
        public DbSet<TS140> TS140 { get; set; }
        public DbSet<Loop_LX_141> Loop_LX_141 { get; set; }
        public DbSet<Loop_N1_141> Loop_N1_141 { get; set; }
        public DbSet<Loop_TDS_141> Loop_TDS_141 { get; set; }
        public DbSet<TS141> TS141 { get; set; }
        public DbSet<Loop_AMT_142> Loop_AMT_142 { get; set; }
        public DbSet<Loop_CID_142> Loop_CID_142 { get; set; }
        public DbSet<Loop_IT1_142> Loop_IT1_142 { get; set; }
        public DbSet<Loop_LIN_142> Loop_LIN_142 { get; set; }
        public DbSet<Loop_LX_142> Loop_LX_142 { get; set; }
        public DbSet<Loop_MEA_142> Loop_MEA_142 { get; set; }
        public DbSet<Loop_N1_142> Loop_N1_142 { get; set; }
        public DbSet<Loop_N1_142_2> Loop_N1_142_2 { get; set; }
        public DbSet<Loop_PRR_142> Loop_PRR_142 { get; set; }
        public DbSet<Loop_REP_142> Loop_REP_142 { get; set; }
        public DbSet<Loop_TDS_142> Loop_TDS_142 { get; set; }
        public DbSet<TS142> TS142 { get; set; }
        public DbSet<Loop_ITA_143> Loop_ITA_143 { get; set; }
        public DbSet<Loop_LIN_143> Loop_LIN_143 { get; set; }
        public DbSet<Loop_N1_143> Loop_N1_143 { get; set; }
        public DbSet<Loop_N1_143_2> Loop_N1_143_2 { get; set; }
        public DbSet<Loop_N1_143_3> Loop_N1_143_3 { get; set; }
        public DbSet<Loop_N9_143> Loop_N9_143 { get; set; }
        public DbSet<Loop_PRR_143> Loop_PRR_143 { get; set; }
        public DbSet<Loop_PRR_143_2> Loop_PRR_143_2 { get; set; }
        public DbSet<Loop_PRT_143> Loop_PRT_143 { get; set; }
        public DbSet<Loop_REP_143> Loop_REP_143 { get; set; }
        public DbSet<Loop_REP_143_2> Loop_REP_143_2 { get; set; }
        public DbSet<Loop_SLN_143> Loop_SLN_143 { get; set; }
        public DbSet<TS143> TS143 { get; set; }
        public DbSet<Loop_ENT_144> Loop_ENT_144 { get; set; }
        public DbSet<TS144> TS144 { get; set; }
        public DbSet<Loop_IN1_146> Loop_IN1_146 { get; set; }
        public DbSet<Loop_N1_146> Loop_N1_146 { get; set; }
        public DbSet<TS146> TS146 { get; set; }
        public DbSet<Loop_IN1_147> Loop_IN1_147 { get; set; }
        public DbSet<Loop_N1_147> Loop_N1_147 { get; set; }
        public DbSet<TS147> TS147 { get; set; }
        public DbSet<Loop_AD1_148> Loop_AD1_148 { get; set; }
        public DbSet<Loop_AIN_148> Loop_AIN_148 { get; set; }
        public DbSet<Loop_AMT_148> Loop_AMT_148 { get; set; }
        public DbSet<Loop_ESI_148> Loop_ESI_148 { get; set; }
        public DbSet<Loop_HL_148> Loop_HL_148 { get; set; }
        public DbSet<Loop_INJ_148> Loop_INJ_148 { get; set; }
        public DbSet<Loop_LN_148> Loop_LN_148 { get; set; }
        public DbSet<Loop_NM1_148> Loop_NM1_148 { get; set; }
        public DbSet<TS148> TS148 { get; set; }
        public DbSet<Loop_FGS_151> Loop_FGS_151 { get; set; }
        public DbSet<Loop_TFS_151> Loop_TFS_151 { get; set; }
        public DbSet<TS151> TS151 { get; set; }
        public DbSet<Loop_GRI_152> Loop_GRI_152 { get; set; }
        public DbSet<Loop_N1_152> Loop_N1_152 { get; set; }
        public DbSet<Loop_N1_152_2> Loop_N1_152_2 { get; set; }
        public DbSet<TS152> TS152 { get; set; }
        public DbSet<Loop_LS1_154> Loop_LS1_154 { get; set; }
        public DbSet<Loop_N1_154> Loop_N1_154 { get; set; }
        public DbSet<Loop_N1_154_2> Loop_N1_154_2 { get; set; }
        public DbSet<TS154> TS154 { get; set; }
        public DbSet<Loop_NM1_161> Loop_NM1_161 { get; set; }
        public DbSet<TS161> TS161 { get; set; }
        public DbSet<Loop_DTM_170> Loop_DTM_170 { get; set; }
        public DbSet<Loop_LX_170> Loop_LX_170 { get; set; }
        public DbSet<Loop_THE_170> Loop_THE_170 { get; set; }
        public DbSet<TS170> TS170 { get; set; }
        public DbSet<Loop_BLI_180> Loop_BLI_180 { get; set; }
        public DbSet<Loop_LM_180> Loop_LM_180 { get; set; }
        public DbSet<Loop_LX_180> Loop_LX_180 { get; set; }
        public DbSet<Loop_N1_180> Loop_N1_180 { get; set; }
        public DbSet<Loop_QTY_180> Loop_QTY_180 { get; set; }
        public DbSet<TS180> TS180 { get; set; }
        public DbSet<Loop_ACT_186> Loop_ACT_186 { get; set; }
        public DbSet<Loop_LIN_186> Loop_LIN_186 { get; set; }
        public DbSet<Loop_LTR_186> Loop_LTR_186 { get; set; }
        public DbSet<Loop_NM1_186> Loop_NM1_186 { get; set; }
        public DbSet<Loop_NM1_186_2> Loop_NM1_186_2 { get; set; }
        public DbSet<Loop_SPK_186> Loop_SPK_186 { get; set; }
        public DbSet<TS186> TS186 { get; set; }
        public DbSet<Loop_ENT_190> Loop_ENT_190 { get; set; }
        public DbSet<TS190> TS190 { get; set; }
        public DbSet<Loop_G61_196> Loop_G61_196 { get; set; }
        public DbSet<Loop_HL_196> Loop_HL_196 { get; set; }
        public DbSet<Loop_N1_196> Loop_N1_196 { get; set; }
        public DbSet<Loop_PD_196> Loop_PD_196 { get; set; }
        public DbSet<TS196> TS196 { get; set; }
        public DbSet<Loop_G61_204> Loop_G61_204 { get; set; }
        public DbSet<Loop_LH1_204> Loop_LH1_204 { get; set; }
        public DbSet<Loop_LX_204> Loop_LX_204 { get; set; }
        public DbSet<Loop_N1_204> Loop_N1_204 { get; set; }
        public DbSet<Loop_N1_204_2> Loop_N1_204_2 { get; set; }
        public DbSet<Loop_N7_204> Loop_N7_204 { get; set; }
        public DbSet<Loop_S5_204> Loop_S5_204 { get; set; }
        public DbSet<TS204> TS204 { get; set; }
        public DbSet<Loop_LX_210> Loop_LX_210 { get; set; }
        public DbSet<Loop_N1_210> Loop_N1_210 { get; set; }
        public DbSet<Loop_N1_210_2> Loop_N1_210_2 { get; set; }
        public DbSet<Loop_N7_210> Loop_N7_210 { get; set; }
        public DbSet<Loop_S5_210> Loop_S5_210 { get; set; }
        public DbSet<TS210> TS210 { get; set; }
        public DbSet<Loop_N1_213> Loop_N1_213 { get; set; }
        public DbSet<TS213> TS213 { get; set; }
        public DbSet<Loop_LX_214> Loop_LX_214 { get; set; }
        public DbSet<Loop_N1_214> Loop_N1_214 { get; set; }
        public DbSet<TS214> TS214 { get; set; }
        public DbSet<Loop_LS_217> Loop_LS_217 { get; set; }
        public DbSet<Loop_LX_217> Loop_LX_217 { get; set; }
        public DbSet<Loop_LX_217_2> Loop_LX_217_2 { get; set; }
        public DbSet<Loop_N1_217> Loop_N1_217 { get; set; }
        public DbSet<Loop_N1_217_2> Loop_N1_217_2 { get; set; }
        public DbSet<TS217> TS217 { get; set; }
        public DbSet<Loop_CL_218> Loop_CL_218 { get; set; }
        public DbSet<Loop_CL_218_2> Loop_CL_218_2 { get; set; }
        public DbSet<Loop_LS_218> Loop_LS_218 { get; set; }
        public DbSet<Loop_LS_218_10> Loop_LS_218_10 { get; set; }
        public DbSet<Loop_LS_218_11> Loop_LS_218_11 { get; set; }
        public DbSet<Loop_LS_218_12> Loop_LS_218_12 { get; set; }
        public DbSet<Loop_LS_218_13> Loop_LS_218_13 { get; set; }
        public DbSet<Loop_LS_218_2> Loop_LS_218_2 { get; set; }
        public DbSet<Loop_LS_218_3> Loop_LS_218_3 { get; set; }
        public DbSet<Loop_LS_218_4> Loop_LS_218_4 { get; set; }
        public DbSet<Loop_LS_218_5> Loop_LS_218_5 { get; set; }
        public DbSet<Loop_LS_218_6> Loop_LS_218_6 { get; set; }
        public DbSet<Loop_LS_218_7> Loop_LS_218_7 { get; set; }
        public DbSet<Loop_LS_218_8> Loop_LS_218_8 { get; set; }
        public DbSet<Loop_LS_218_9> Loop_LS_218_9 { get; set; }
        public DbSet<Loop_LX_218> Loop_LX_218 { get; set; }
        public DbSet<Loop_LX_218_2> Loop_LX_218_2 { get; set; }
        public DbSet<Loop_LX_218_3> Loop_LX_218_3 { get; set; }
        public DbSet<Loop_LX_218_4> Loop_LX_218_4 { get; set; }
        public DbSet<Loop_LX_218_5> Loop_LX_218_5 { get; set; }
        public DbSet<Loop_LX_218_6> Loop_LX_218_6 { get; set; }
        public DbSet<Loop_LX_218_7> Loop_LX_218_7 { get; set; }
        public DbSet<Loop_LX_218_8> Loop_LX_218_8 { get; set; }
        public DbSet<Loop_N1_218> Loop_N1_218 { get; set; }
        public DbSet<Loop_SCL_218> Loop_SCL_218 { get; set; }
        public DbSet<Loop_SCL_218_2> Loop_SCL_218_2 { get; set; }
        public DbSet<Loop_SCL_218_3> Loop_SCL_218_3 { get; set; }
        public DbSet<Loop_SCL_218_4> Loop_SCL_218_4 { get; set; }
        public DbSet<Loop_SCL_218_5> Loop_SCL_218_5 { get; set; }
        public DbSet<Loop_TS_218> Loop_TS_218 { get; set; }
        public DbSet<TS218> TS218 { get; set; }
        public DbSet<Loop_N1_250> Loop_N1_250 { get; set; }
        public DbSet<Loop_PRF_250> Loop_PRF_250 { get; set; }
        public DbSet<TS250> TS250 { get; set; }
        public DbSet<Loop_LX_251> Loop_LX_251 { get; set; }
        public DbSet<Loop_N1_251> Loop_N1_251 { get; set; }
        public DbSet<Loop_N1_251_2> Loop_N1_251_2 { get; set; }
        public DbSet<Loop_PD_251> Loop_PD_251 { get; set; }
        public DbSet<Loop_PD_251_2> Loop_PD_251_2 { get; set; }
        public DbSet<Loop_PL_251> Loop_PL_251 { get; set; }
        public DbSet<Loop_PO1_251> Loop_PO1_251 { get; set; }
        public DbSet<Loop_PPL_251> Loop_PPL_251 { get; set; }
        public DbSet<TS251> TS251 { get; set; }
        public DbSet<Loop_CSI_260> Loop_CSI_260 { get; set; }
        public DbSet<Loop_DFI_260> Loop_DFI_260 { get; set; }
        public DbSet<Loop_FCL_260> Loop_FCL_260 { get; set; }
        public DbSet<Loop_FIS_260> Loop_FIS_260 { get; set; }
        public DbSet<Loop_N1_260> Loop_N1_260 { get; set; }
        public DbSet<Loop_REC_260> Loop_REC_260 { get; set; }
        public DbSet<TS260> TS260 { get; set; }
        public DbSet<Loop_G63_263> Loop_G63_263 { get; set; }
        public DbSet<Loop_LX_263> Loop_LX_263 { get; set; }
        public DbSet<Loop_REF_263> Loop_REF_263 { get; set; }
        public DbSet<TS263> TS263 { get; set; }
        public DbSet<Loop_DTP_264> Loop_DTP_264 { get; set; }
        public DbSet<Loop_LS_264> Loop_LS_264 { get; set; }
        public DbSet<Loop_LX_264> Loop_LX_264 { get; set; }
        public DbSet<Loop_N1_264> Loop_N1_264 { get; set; }
        public DbSet<Loop_N1_264_2> Loop_N1_264_2 { get; set; }
        public DbSet<Loop_REC_264> Loop_REC_264 { get; set; }
        public DbSet<TS264> TS264 { get; set; }
        public DbSet<Loop_EQ_270> Loop_EQ_270 { get; set; }
        public DbSet<Loop_HL_270> Loop_HL_270 { get; set; }
        public DbSet<Loop_NM1_270> Loop_NM1_270 { get; set; }
        public DbSet<TS270> TS270 { get; set; }
        public DbSet<Loop_EB_271> Loop_EB_271 { get; set; }
        public DbSet<Loop_HL_271> Loop_HL_271 { get; set; }
        public DbSet<Loop_LS_271> Loop_LS_271 { get; set; }
        public DbSet<Loop_NM1_271> Loop_NM1_271 { get; set; }
        public DbSet<Loop_NM1_271_2> Loop_NM1_271_2 { get; set; }
        public DbSet<TS271> TS271 { get; set; }
        public DbSet<Loop_III_272> Loop_III_272 { get; set; }
        public DbSet<Loop_LID_272> Loop_LID_272 { get; set; }
        public DbSet<Loop_LIE_272> Loop_LIE_272 { get; set; }
        public DbSet<Loop_LQ_272> Loop_LQ_272 { get; set; }
        public DbSet<Loop_LQ_272_2> Loop_LQ_272_2 { get; set; }
        public DbSet<Loop_LS_272> Loop_LS_272 { get; set; }
        public DbSet<Loop_LS_272_2> Loop_LS_272_2 { get; set; }
        public DbSet<Loop_LS_272_3> Loop_LS_272_3 { get; set; }
        public DbSet<Loop_LX_272> Loop_LX_272 { get; set; }
        public DbSet<Loop_N9_272> Loop_N9_272 { get; set; }
        public DbSet<Loop_NM1_272> Loop_NM1_272 { get; set; }
        public DbSet<Loop_NM1_272_2> Loop_NM1_272_2 { get; set; }
        public DbSet<Loop_NM1_272_3> Loop_NM1_272_3 { get; set; }
        public DbSet<Loop_NX1_272> Loop_NX1_272 { get; set; }
        public DbSet<Loop_PIN_272> Loop_PIN_272 { get; set; }
        public DbSet<Loop_PWK_272> Loop_PWK_272 { get; set; }
        public DbSet<TS272> TS272 { get; set; }
        public DbSet<Loop_HL_276> Loop_HL_276 { get; set; }
        public DbSet<Loop_NM1_276> Loop_NM1_276 { get; set; }
        public DbSet<Loop_NM1_276_2> Loop_NM1_276_2 { get; set; }
        public DbSet<Loop_SVC_276> Loop_SVC_276 { get; set; }
        public DbSet<Loop_TRN_276> Loop_TRN_276 { get; set; }
        public DbSet<TS276> TS276 { get; set; }
        public DbSet<Loop_HL_277> Loop_HL_277 { get; set; }
        public DbSet<Loop_NM1_277> Loop_NM1_277 { get; set; }
        public DbSet<Loop_NM1_277_2> Loop_NM1_277_2 { get; set; }
        public DbSet<Loop_PWK_277> Loop_PWK_277 { get; set; }
        public DbSet<Loop_SVC_277> Loop_SVC_277 { get; set; }
        public DbSet<Loop_TRN_277> Loop_TRN_277 { get; set; }
        public DbSet<TS277> TS277 { get; set; }
        public DbSet<Loop_MI_290> Loop_MI_290 { get; set; }
        public DbSet<Loop_N1_290> Loop_N1_290 { get; set; }
        public DbSet<Loop_N1_290_2> Loop_N1_290_2 { get; set; }
        public DbSet<TS290> TS290 { get; set; }
        public DbSet<Loop_H1_300> Loop_H1_300 { get; set; }
        public DbSet<Loop_LX_300> Loop_LX_300 { get; set; }
        public DbSet<Loop_N1_300> Loop_N1_300 { get; set; }
        public DbSet<Loop_R4_300> Loop_R4_300 { get; set; }
        public DbSet<Loop_Y2_300> Loop_Y2_300 { get; set; }
        public DbSet<TS300> TS300 { get; set; }
        public DbSet<Loop_H1_301> Loop_H1_301 { get; set; }
        public DbSet<Loop_LX_301> Loop_LX_301 { get; set; }
        public DbSet<Loop_N1_301> Loop_N1_301 { get; set; }
        public DbSet<Loop_N1_301_2> Loop_N1_301_2 { get; set; }
        public DbSet<Loop_R4_301> Loop_R4_301 { get; set; }
        public DbSet<Loop_Y4_301> Loop_Y4_301 { get; set; }
        public DbSet<TS301> TS301 { get; set; }
        public DbSet<TS303> TS303 { get; set; }
        public DbSet<Loop_C8_304> Loop_C8_304 { get; set; }
        public DbSet<Loop_H1_304> Loop_H1_304 { get; set; }
        public DbSet<Loop_L0_304> Loop_L0_304 { get; set; }
        public DbSet<Loop_L1_304> Loop_L1_304 { get; set; }
        public DbSet<Loop_L3_304> Loop_L3_304 { get; set; }
        public DbSet<Loop_LH1_304> Loop_LH1_304 { get; set; }
        public DbSet<Loop_LX_304> Loop_LX_304 { get; set; }
        public DbSet<Loop_N1_304> Loop_N1_304 { get; set; }
        public DbSet<Loop_N7_304> Loop_N7_304 { get; set; }
        public DbSet<Loop_PAL_304> Loop_PAL_304 { get; set; }
        public DbSet<Loop_R4_304> Loop_R4_304 { get; set; }
        public DbSet<TS304> TS304 { get; set; }
        public DbSet<Loop_H1_309> Loop_H1_309 { get; set; }
        public DbSet<Loop_LX_309> Loop_LX_309 { get; set; }
        public DbSet<Loop_M12_309> Loop_M12_309 { get; set; }
        public DbSet<Loop_N1_309> Loop_N1_309 { get; set; }
        public DbSet<Loop_N10_309> Loop_N10_309 { get; set; }
        public DbSet<Loop_P4_309> Loop_P4_309 { get; set; }
        public DbSet<Loop_VID_309> Loop_VID_309 { get; set; }
        public DbSet<TS309> TS309 { get; set; }
        public DbSet<Loop_C8_310> Loop_C8_310 { get; set; }
        public DbSet<Loop_H1_310> Loop_H1_310 { get; set; }
        public DbSet<Loop_L0_310> Loop_L0_310 { get; set; }
        public DbSet<Loop_L1_310> Loop_L1_310 { get; set; }
        public DbSet<Loop_LX_310> Loop_LX_310 { get; set; }
        public DbSet<Loop_N1_310> Loop_N1_310 { get; set; }
        public DbSet<Loop_N7_310> Loop_N7_310 { get; set; }
        public DbSet<Loop_R4_310> Loop_R4_310 { get; set; }
        public DbSet<TS310> TS310 { get; set; }
        public DbSet<Loop_ED_311> Loop_ED_311 { get; set; }
        public DbSet<Loop_L0_311> Loop_L0_311 { get; set; }
        public DbSet<Loop_LX_311> Loop_LX_311 { get; set; }
        public DbSet<Loop_N1_311> Loop_N1_311 { get; set; }
        public DbSet<TS311> TS311 { get; set; }
        public DbSet<Loop_H1_312> Loop_H1_312 { get; set; }
        public DbSet<Loop_L0_312> Loop_L0_312 { get; set; }
        public DbSet<Loop_L1_312> Loop_L1_312 { get; set; }
        public DbSet<Loop_LX_312> Loop_LX_312 { get; set; }
        public DbSet<Loop_N1_312> Loop_N1_312 { get; set; }
        public DbSet<Loop_N7_312> Loop_N7_312 { get; set; }
        public DbSet<Loop_R4_312> Loop_R4_312 { get; set; }
        public DbSet<TS312> TS312 { get; set; }
        public DbSet<TS313> TS313 { get; set; }
        public DbSet<Loop_R4_315> Loop_R4_315 { get; set; }
        public DbSet<TS315> TS315 { get; set; }
        public DbSet<Loop_L0_317> Loop_L0_317 { get; set; }
        public DbSet<Loop_N1_317> Loop_N1_317 { get; set; }
        public DbSet<TS317> TS317 { get; set; }
        public DbSet<TS319> TS319 { get; set; }
        public DbSet<Loop_L0_322> Loop_L0_322 { get; set; }
        public DbSet<Loop_R4_322> Loop_R4_322 { get; set; }
        public DbSet<TS322> TS322 { get; set; }
        public DbSet<Loop_R4_323> Loop_R4_323 { get; set; }
        public DbSet<TS323> TS323 { get; set; }
        public DbSet<Loop_N7_324> Loop_N7_324 { get; set; }
        public DbSet<Loop_R4_324> Loop_R4_324 { get; set; }
        public DbSet<TS324> TS324 { get; set; }
        public DbSet<Loop_H1_325> Loop_H1_325 { get; set; }
        public DbSet<Loop_LIN_325> Loop_LIN_325 { get; set; }
        public DbSet<Loop_MBL_325> Loop_MBL_325 { get; set; }
        public DbSet<Loop_N1_325> Loop_N1_325 { get; set; }
        public DbSet<TS325> TS325 { get; set; }
        public DbSet<Loop_N7_326> Loop_N7_326 { get; set; }
        public DbSet<Loop_R4_326> Loop_R4_326 { get; set; }
        public DbSet<Loop_V1_326> Loop_V1_326 { get; set; }
        public DbSet<TS326> TS326 { get; set; }
        public DbSet<Loop_P4_350> Loop_P4_350 { get; set; }
        public DbSet<Loop_X4_350> Loop_X4_350 { get; set; }
        public DbSet<TS350> TS350 { get; set; }
        public DbSet<Loop_M14_352> Loop_M14_352 { get; set; }
        public DbSet<Loop_P4_352> Loop_P4_352 { get; set; }
        public DbSet<TS352> TS352 { get; set; }
        public DbSet<TS353> TS353 { get; set; }
        public DbSet<Loop_P4_354> Loop_P4_354 { get; set; }
        public DbSet<TS354> TS354 { get; set; }
        public DbSet<Loop_H1_355> Loop_H1_355 { get; set; }
        public DbSet<Loop_H2_355> Loop_H2_355 { get; set; }
        public DbSet<Loop_LX_355> Loop_LX_355 { get; set; }
        public DbSet<Loop_M11_355> Loop_M11_355 { get; set; }
        public DbSet<Loop_M12_355> Loop_M12_355 { get; set; }
        public DbSet<Loop_M13_355> Loop_M13_355 { get; set; }
        public DbSet<Loop_M14_355> Loop_M14_355 { get; set; }
        public DbSet<Loop_M15_355> Loop_M15_355 { get; set; }
        public DbSet<Loop_M20_355> Loop_M20_355 { get; set; }
        public DbSet<Loop_M21_355> Loop_M21_355 { get; set; }
        public DbSet<Loop_MBL_355> Loop_MBL_355 { get; set; }
        public DbSet<Loop_N1_355> Loop_N1_355 { get; set; }
        public DbSet<Loop_N10_355> Loop_N10_355 { get; set; }
        public DbSet<Loop_N3_355> Loop_N3_355 { get; set; }
        public DbSet<Loop_P4_355> Loop_P4_355 { get; set; }
        public DbSet<Loop_P5_355> Loop_P5_355 { get; set; }
        public DbSet<Loop_VID_355> Loop_VID_355 { get; set; }
        public DbSet<TS355> TS355 { get; set; }
        public DbSet<TS356> TS356 { get; set; }
        public DbSet<Loop_CI_361> Loop_CI_361 { get; set; }
        public DbSet<TS361> TS361 { get; set; }
        public DbSet<Loop_LH1_404> Loop_LH1_404 { get; set; }
        public DbSet<Loop_LS_404> Loop_LS_404 { get; set; }
        public DbSet<Loop_LS_404_2> Loop_LS_404_2 { get; set; }
        public DbSet<Loop_LX_404> Loop_LX_404 { get; set; }
        public DbSet<Loop_LX_404_2> Loop_LX_404_2 { get; set; }
        public DbSet<Loop_N1_404> Loop_N1_404 { get; set; }
        public DbSet<Loop_N1_404_2> Loop_N1_404_2 { get; set; }
        public DbSet<Loop_N7_404> Loop_N7_404 { get; set; }
        public DbSet<Loop_S1_404> Loop_S1_404 { get; set; }
        public DbSet<Loop_T1_404> Loop_T1_404 { get; set; }
        public DbSet<Loop_VC_404> Loop_VC_404 { get; set; }
        public DbSet<TS404> TS404 { get; set; }
        public DbSet<Loop_LS_410> Loop_LS_410 { get; set; }
        public DbSet<Loop_LX_410> Loop_LX_410 { get; set; }
        public DbSet<Loop_LX_410_2> Loop_LX_410_2 { get; set; }
        public DbSet<Loop_N1_410> Loop_N1_410 { get; set; }
        public DbSet<Loop_N7_410> Loop_N7_410 { get; set; }
        public DbSet<Loop_S1_410> Loop_S1_410 { get; set; }
        public DbSet<Loop_T1_410> Loop_T1_410 { get; set; }
        public DbSet<TS410> TS410 { get; set; }
        public DbSet<Loop_CIC_414> Loop_CIC_414 { get; set; }
        public DbSet<Loop_CTC_414> Loop_CTC_414 { get; set; }
        public DbSet<Loop_LX_414> Loop_LX_414 { get; set; }
        public DbSet<TS414> TS414 { get; set; }
        public DbSet<Loop_LH1_417> Loop_LH1_417 { get; set; }
        public DbSet<Loop_LS_417> Loop_LS_417 { get; set; }
        public DbSet<Loop_LS_417_2> Loop_LS_417_2 { get; set; }
        public DbSet<Loop_LX_417> Loop_LX_417 { get; set; }
        public DbSet<Loop_LX_417_2> Loop_LX_417_2 { get; set; }
        public DbSet<Loop_N1_417> Loop_N1_417 { get; set; }
        public DbSet<Loop_N1_417_2> Loop_N1_417_2 { get; set; }
        public DbSet<Loop_N7_417> Loop_N7_417 { get; set; }
        public DbSet<Loop_S1_417> Loop_S1_417 { get; set; }
        public DbSet<Loop_T1_417> Loop_T1_417 { get; set; }
        public DbSet<Loop_VC_417> Loop_VC_417 { get; set; }
        public DbSet<TS417> TS417 { get; set; }
        public DbSet<Loop_LH1_418> Loop_LH1_418 { get; set; }
        public DbSet<Loop_LS_418> Loop_LS_418 { get; set; }
        public DbSet<Loop_W1_418> Loop_W1_418 { get; set; }
        public DbSet<Loop_W2_418> Loop_W2_418 { get; set; }
        public DbSet<TS418> TS418 { get; set; }
        public DbSet<Loop_E6_419> Loop_E6_419 { get; set; }
        public DbSet<TS419> TS419 { get; set; }
        public DbSet<Loop_E6_420> Loop_E6_420 { get; set; }
        public DbSet<TS420> TS420 { get; set; }
        public DbSet<Loop_IS2_421> Loop_IS2_421 { get; set; }
        public DbSet<TS421> TS421 { get; set; }
        public DbSet<Loop_F9_422> Loop_F9_422 { get; set; }
        public DbSet<Loop_LX_422> Loop_LX_422 { get; set; }
        public DbSet<Loop_N7_422> Loop_N7_422 { get; set; }
        public DbSet<Loop_SCO_422> Loop_SCO_422 { get; set; }
        public DbSet<TS422> TS422 { get; set; }
        public DbSet<Loop_ZT_425> Loop_ZT_425 { get; set; }
        public DbSet<TS425> TS425 { get; set; }
        public DbSet<Loop_BNX_426> Loop_BNX_426 { get; set; }
        public DbSet<Loop_L0_426> Loop_L0_426 { get; set; }
        public DbSet<Loop_LX_426> Loop_LX_426 { get; set; }
        public DbSet<Loop_N1_426> Loop_N1_426 { get; set; }
        public DbSet<Loop_N7_426> Loop_N7_426 { get; set; }
        public DbSet<Loop_R2_426> Loop_R2_426 { get; set; }
        public DbSet<Loop_R2B_426> Loop_R2B_426 { get; set; }
        public DbSet<Loop_S1_426> Loop_S1_426 { get; set; }
        public DbSet<Loop_T1_426> Loop_T1_426 { get; set; }
        public DbSet<TS426> TS426 { get; set; }
        public DbSet<Loop_RU2_429> Loop_RU2_429 { get; set; }
        public DbSet<TS429> TS429 { get; set; }
        public DbSet<TS431> TS431 { get; set; }
        public DbSet<TS440> TS440 { get; set; }
        public DbSet<TS466> TS466 { get; set; }
        public DbSet<Loop_JL_468> Loop_JL_468 { get; set; }
        public DbSet<TS468> TS468 { get; set; }
        public DbSet<Loop_MC_485> Loop_MC_485 { get; set; }
        public DbSet<Loop_RA_485> Loop_RA_485 { get; set; }
        public DbSet<Loop_SC_485> Loop_SC_485 { get; set; }
        public DbSet<TS485> TS485 { get; set; }
        public DbSet<Loop_PT_490> Loop_PT_490 { get; set; }
        public DbSet<TS490> TS490 { get; set; }
        public DbSet<Loop_SC_492> Loop_SC_492 { get; set; }
        public DbSet<TS492> TS492 { get; set; }
        public DbSet<TS494> TS494 { get; set; }
        public DbSet<Loop_LM_511> Loop_LM_511 { get; set; }
        public DbSet<Loop_LX_511> Loop_LX_511 { get; set; }
        public DbSet<Loop_N1_511> Loop_N1_511 { get; set; }
        public DbSet<Loop_PO1_511> Loop_PO1_511 { get; set; }
        public DbSet<Loop_QTY_511> Loop_QTY_511 { get; set; }
        public DbSet<Loop_REF_511> Loop_REF_511 { get; set; }
        public DbSet<TS511> TS511 { get; set; }
        public DbSet<Loop_LM_517> Loop_LM_517 { get; set; }
        public DbSet<Loop_N1_517> Loop_N1_517 { get; set; }
        public DbSet<Loop_QTY_517> Loop_QTY_517 { get; set; }
        public DbSet<TS517> TS517 { get; set; }
        public DbSet<Loop_CS_527> Loop_CS_527 { get; set; }
        public DbSet<Loop_LIN_527> Loop_LIN_527 { get; set; }
        public DbSet<Loop_LM_527> Loop_LM_527 { get; set; }
        public DbSet<Loop_N1_527> Loop_N1_527 { get; set; }
        public DbSet<Loop_N1_527_2> Loop_N1_527_2 { get; set; }
        public DbSet<Loop_QTY_527> Loop_QTY_527 { get; set; }
        public DbSet<Loop_RCD_527> Loop_RCD_527 { get; set; }
        public DbSet<Loop_REF_527> Loop_REF_527 { get; set; }
        public DbSet<TS527> TS527 { get; set; }
        public DbSet<Loop_HL_536> Loop_HL_536 { get; set; }
        public DbSet<Loop_LM_536> Loop_LM_536 { get; set; }
        public DbSet<Loop_N1_536> Loop_N1_536 { get; set; }
        public DbSet<TS536> TS536 { get; set; }
        public DbSet<Loop_AT_561> Loop_AT_561 { get; set; }
        public DbSet<Loop_HL_561> Loop_HL_561 { get; set; }
        public DbSet<Loop_LM_561> Loop_LM_561 { get; set; }
        public DbSet<Loop_N1_561> Loop_N1_561 { get; set; }
        public DbSet<Loop_N1_561_2> Loop_N1_561_2 { get; set; }
        public DbSet<Loop_SCH_561> Loop_SCH_561 { get; set; }
        public DbSet<TS561> TS561 { get; set; }
        public DbSet<Loop_CS_567> Loop_CS_567 { get; set; }
        public DbSet<Loop_LM_567> Loop_LM_567 { get; set; }
        public DbSet<Loop_N1_567> Loop_N1_567 { get; set; }
        public DbSet<TS567> TS567 { get; set; }
        public DbSet<Loop_CS_568> Loop_CS_568 { get; set; }
        public DbSet<Loop_LM_568> Loop_LM_568 { get; set; }
        public DbSet<Loop_LX_568> Loop_LX_568 { get; set; }
        public DbSet<Loop_N1_568> Loop_N1_568 { get; set; }
        public DbSet<Loop_N1_568_2> Loop_N1_568_2 { get; set; }
        public DbSet<Loop_REF_568> Loop_REF_568 { get; set; }
        public DbSet<TS568> TS568 { get; set; }
        public DbSet<TS601> TS601 { get; set; }
        public DbSet<Loop_LX_602> Loop_LX_602 { get; set; }
        public DbSet<Loop_N1_602> Loop_N1_602 { get; set; }
        public DbSet<Loop_PR_602> Loop_PR_602 { get; set; }
        public DbSet<Loop_RA_602> Loop_RA_602 { get; set; }
        public DbSet<Loop_RH_602> Loop_RH_602 { get; set; }
        public DbSet<Loop_SB_602> Loop_SB_602 { get; set; }
        public DbSet<Loop_SC_602> Loop_SC_602 { get; set; }
        public DbSet<Loop_SRM_602> Loop_SRM_602 { get; set; }
        public DbSet<Loop_SRT_602> Loop_SRT_602 { get; set; }
        public DbSet<TS602> TS602 { get; set; }
        public DbSet<Loop_N1_622> Loop_N1_622 { get; set; }
        public DbSet<Loop_W2A_622> Loop_W2A_622 { get; set; }
        public DbSet<TS622> TS622 { get; set; }
        public DbSet<Loop_CB1_805> Loop_CB1_805 { get; set; }
        public DbSet<Loop_CBS_805> Loop_CBS_805 { get; set; }
        public DbSet<Loop_HL_805> Loop_HL_805 { get; set; }
        public DbSet<Loop_LX_805> Loop_LX_805 { get; set; }
        public DbSet<Loop_N1_805> Loop_N1_805 { get; set; }
        public DbSet<Loop_N1_805_2> Loop_N1_805_2 { get; set; }
        public DbSet<Loop_N1_805_3> Loop_N1_805_3 { get; set; }
        public DbSet<Loop_PD_805> Loop_PD_805 { get; set; }
        public DbSet<TS805> TS805 { get; set; }
        public DbSet<Loop_CAL_806> Loop_CAL_806 { get; set; }
        public DbSet<Loop_N1_806> Loop_N1_806 { get; set; }
        public DbSet<Loop_TID_806> Loop_TID_806 { get; set; }
        public DbSet<TS806> TS806 { get; set; }
        public DbSet<Loop_IT1_810> Loop_IT1_810 { get; set; }
        public DbSet<Loop_LM_810> Loop_LM_810 { get; set; }
        public DbSet<Loop_N1_810> Loop_N1_810 { get; set; }
        public DbSet<Loop_N9_810> Loop_N9_810 { get; set; }
        public DbSet<Loop_PID_810> Loop_PID_810 { get; set; }
        public DbSet<Loop_SAC_810> Loop_SAC_810 { get; set; }
        public DbSet<Loop_SLN_810> Loop_SLN_810 { get; set; }
        public DbSet<TS810> TS810 { get; set; }
        public DbSet<Loop_BAL_811> Loop_BAL_811 { get; set; }
        public DbSet<Loop_HL_811> Loop_HL_811 { get; set; }
        public DbSet<Loop_IT1_811> Loop_IT1_811 { get; set; }
        public DbSet<Loop_ITA_811> Loop_ITA_811 { get; set; }
        public DbSet<Loop_ITA_811_2> Loop_ITA_811_2 { get; set; }
        public DbSet<Loop_LX_811> Loop_LX_811 { get; set; }
        public DbSet<Loop_N1_811> Loop_N1_811 { get; set; }
        public DbSet<Loop_N1_811_2> Loop_N1_811_2 { get; set; }
        public DbSet<Loop_N1_811_3> Loop_N1_811_3 { get; set; }
        public DbSet<Loop_N1_811_4> Loop_N1_811_4 { get; set; }
        public DbSet<Loop_QTY_811> Loop_QTY_811 { get; set; }
        public DbSet<Loop_SLN_811> Loop_SLN_811 { get; set; }
        public DbSet<Loop_TCD_811> Loop_TCD_811 { get; set; }
        public DbSet<Loop_USD_811> Loop_USD_811 { get; set; }
        public DbSet<TS811> TS811 { get; set; }
        public DbSet<Loop_CDD_812> Loop_CDD_812 { get; set; }
        public DbSet<Loop_LM_812> Loop_LM_812 { get; set; }
        public DbSet<Loop_N1_812> Loop_N1_812 { get; set; }
        public DbSet<TS812> TS812 { get; set; }
        public DbSet<Loop_FGS_813> Loop_FGS_813 { get; set; }
        public DbSet<Loop_N1_813> Loop_N1_813 { get; set; }
        public DbSet<Loop_N1_813_2> Loop_N1_813_2 { get; set; }
        public DbSet<Loop_TFS_813> Loop_TFS_813 { get; set; }
        public DbSet<Loop_TIA_813> Loop_TIA_813 { get; set; }
        public DbSet<TS813> TS813 { get; set; }
        public DbSet<TS815> TS815 { get; set; }
        public DbSet<Loop_HL_816> Loop_HL_816 { get; set; }
        public DbSet<Loop_N1_816> Loop_N1_816 { get; set; }
        public DbSet<Loop_N1_816_2> Loop_N1_816_2 { get; set; }
        public DbSet<TS816> TS816 { get; set; }
        public DbSet<Loop_LIN_818> Loop_LIN_818 { get; set; }
        public DbSet<Loop_N1_818> Loop_N1_818 { get; set; }
        public DbSet<Loop_N11_818> Loop_N11_818 { get; set; }
        public DbSet<TS818> TS818 { get; set; }
        public DbSet<Loop_JID_819> Loop_JID_819 { get; set; }
        public DbSet<Loop_JIL_819> Loop_JIL_819 { get; set; }
        public DbSet<Loop_N1_819> Loop_N1_819 { get; set; }
        public DbSet<Loop_PSA_819> Loop_PSA_819 { get; set; }
        public DbSet<TS819> TS819 { get; set; }
        public DbSet<Loop_ADX_820> Loop_ADX_820 { get; set; }
        public DbSet<Loop_ADX_820_2> Loop_ADX_820_2 { get; set; }
        public DbSet<Loop_AIN_820> Loop_AIN_820 { get; set; }
        public DbSet<Loop_ENT_820> Loop_ENT_820 { get; set; }
        public DbSet<Loop_INV_820> Loop_INV_820 { get; set; }
        public DbSet<Loop_IT1_820> Loop_IT1_820 { get; set; }
        public DbSet<Loop_ITA_820> Loop_ITA_820 { get; set; }
        public DbSet<Loop_LX_820> Loop_LX_820 { get; set; }
        public DbSet<Loop_N1_820> Loop_N1_820 { get; set; }
        public DbSet<Loop_NM1_820> Loop_NM1_820 { get; set; }
        public DbSet<Loop_PEN_820> Loop_PEN_820 { get; set; }
        public DbSet<Loop_REF_820> Loop_REF_820 { get; set; }
        public DbSet<Loop_REF_820_2> Loop_REF_820_2 { get; set; }
        public DbSet<Loop_RMR_820> Loop_RMR_820 { get; set; }
        public DbSet<Loop_SLN_820> Loop_SLN_820 { get; set; }
        public DbSet<Loop_TXP_820> Loop_TXP_820 { get; set; }
        public DbSet<TS820> TS820 { get; set; }
        public DbSet<Loop_ACT_821> Loop_ACT_821 { get; set; }
        public DbSet<Loop_FIR_821> Loop_FIR_821 { get; set; }
        public DbSet<Loop_N1_821> Loop_N1_821 { get; set; }
        public DbSet<TS821> TS821 { get; set; }
        public DbSet<Loop_ACT_822> Loop_ACT_822 { get; set; }
        public DbSet<Loop_BAL_822> Loop_BAL_822 { get; set; }
        public DbSet<Loop_N1_822> Loop_N1_822 { get; set; }
        public DbSet<Loop_RTE_822> Loop_RTE_822 { get; set; }
        public DbSet<Loop_SER_822> Loop_SER_822 { get; set; }
        public DbSet<TS822> TS822 { get; set; }
        public DbSet<Loop_BAT_823> Loop_BAT_823 { get; set; }
        public DbSet<Loop_BPS_823> Loop_BPS_823 { get; set; }
        public DbSet<Loop_DEP_823> Loop_DEP_823 { get; set; }
        public DbSet<Loop_N1_823> Loop_N1_823 { get; set; }
        public DbSet<Loop_RMT_823> Loop_RMT_823 { get; set; }
        public DbSet<TS823> TS823 { get; set; }
        public DbSet<Loop_LM_824> Loop_LM_824 { get; set; }
        public DbSet<Loop_N1_824> Loop_N1_824 { get; set; }
        public DbSet<Loop_OTI_824> Loop_OTI_824 { get; set; }
        public DbSet<Loop_TED_824> Loop_TED_824 { get; set; }
        public DbSet<TS824> TS824 { get; set; }
        public DbSet<Loop_N1_826> Loop_N1_826 { get; set; }
        public DbSet<Loop_TFS_826> Loop_TFS_826 { get; set; }
        public DbSet<TS826> TS826 { get; set; }
        public DbSet<TS827> TS827 { get; set; }
        public DbSet<Loop_N1_828> Loop_N1_828 { get; set; }
        public DbSet<TS828> TS828 { get; set; }
        public DbSet<TS829> TS829 { get; set; }
        public DbSet<Loop_FST_830> Loop_FST_830 { get; set; }
        public DbSet<Loop_LIN_830> Loop_LIN_830 { get; set; }
        public DbSet<Loop_LM_830> Loop_LM_830 { get; set; }
        public DbSet<Loop_N1_830> Loop_N1_830 { get; set; }
        public DbSet<Loop_SDP_830> Loop_SDP_830 { get; set; }
        public DbSet<Loop_SHP_830> Loop_SHP_830 { get; set; }
        public DbSet<Loop_SLN_830> Loop_SLN_830 { get; set; }
        public DbSet<TS830> TS830 { get; set; }
        public DbSet<TS831> TS831 { get; set; }
        public DbSet<Loop_CTP_832> Loop_CTP_832 { get; set; }
        public DbSet<Loop_LIN_832> Loop_LIN_832 { get; set; }
        public DbSet<Loop_N1_832> Loop_N1_832 { get; set; }
        public DbSet<Loop_PKL_832> Loop_PKL_832 { get; set; }
        public DbSet<TS832> TS832 { get; set; }
        public DbSet<Loop_CDA_833> Loop_CDA_833 { get; set; }
        public DbSet<Loop_CRO_833> Loop_CRO_833 { get; set; }
        public DbSet<Loop_EMP_833> Loop_EMP_833 { get; set; }
        public DbSet<Loop_EMS_833> Loop_EMS_833 { get; set; }
        public DbSet<Loop_FAA_833> Loop_FAA_833 { get; set; }
        public DbSet<Loop_IN1_833> Loop_IN1_833 { get; set; }
        public DbSet<Loop_IN1_833_2> Loop_IN1_833_2 { get; set; }
        public DbSet<Loop_LX_833> Loop_LX_833 { get; set; }
        public DbSet<Loop_N1_833> Loop_N1_833 { get; set; }
        public DbSet<Loop_N1_833_2> Loop_N1_833_2 { get; set; }
        public DbSet<Loop_N1_833_3> Loop_N1_833_3 { get; set; }
        public DbSet<Loop_N4_833> Loop_N4_833 { get; set; }
        public DbSet<Loop_NX1_833> Loop_NX1_833 { get; set; }
        public DbSet<Loop_NX1_833_2> Loop_NX1_833_2 { get; set; }
        public DbSet<Loop_REA_833> Loop_REA_833 { get; set; }
        public DbSet<TS833> TS833 { get; set; }
        public DbSet<Loop_ACT_834> Loop_ACT_834 { get; set; }
        public DbSet<Loop_AIN_834> Loop_AIN_834 { get; set; }
        public DbSet<Loop_BEN_834> Loop_BEN_834 { get; set; }
        public DbSet<Loop_COB_834> Loop_COB_834 { get; set; }
        public DbSet<Loop_DSB_834> Loop_DSB_834 { get; set; }
        public DbSet<Loop_FC_834> Loop_FC_834 { get; set; }
        public DbSet<Loop_FSA_834> Loop_FSA_834 { get; set; }
        public DbSet<Loop_HD_834> Loop_HD_834 { get; set; }
        public DbSet<Loop_INS_834> Loop_INS_834 { get; set; }
        public DbSet<Loop_INV_834> Loop_INV_834 { get; set; }
        public DbSet<Loop_LC_834> Loop_LC_834 { get; set; }
        public DbSet<Loop_LX_834> Loop_LX_834 { get; set; }
        public DbSet<Loop_N1_834> Loop_N1_834 { get; set; }
        public DbSet<Loop_N1_834_2> Loop_N1_834_2 { get; set; }
        public DbSet<Loop_NM1_834> Loop_NM1_834 { get; set; }
        public DbSet<Loop_NX1_834> Loop_NX1_834 { get; set; }
        public DbSet<Loop_PER_834> Loop_PER_834 { get; set; }
        public DbSet<Loop_RP_834> Loop_RP_834 { get; set; }
        public DbSet<TS834> TS834 { get; set; }
        public DbSet<Loop_CLP_835> Loop_CLP_835 { get; set; }
        public DbSet<Loop_LX_835> Loop_LX_835 { get; set; }
        public DbSet<Loop_N1_835> Loop_N1_835 { get; set; }
        public DbSet<Loop_SVC_835> Loop_SVC_835 { get; set; }
        public DbSet<TS835> TS835 { get; set; }
        public DbSet<Loop_N1_836> Loop_N1_836 { get; set; }
        public DbSet<Loop_N1_836_2> Loop_N1_836_2 { get; set; }
        public DbSet<Loop_PO1_836> Loop_PO1_836 { get; set; }
        public DbSet<Loop_SLN_836> Loop_SLN_836 { get; set; }
        public DbSet<TS836> TS836 { get; set; }
        public DbSet<Loop_CLM_837> Loop_CLM_837 { get; set; }
        public DbSet<Loop_LIN_837> Loop_LIN_837 { get; set; }
        public DbSet<Loop_LS_837> Loop_LS_837 { get; set; }
        public DbSet<Loop_LS_837_2> Loop_LS_837_2 { get; set; }
        public DbSet<Loop_LX_837> Loop_LX_837 { get; set; }
        public DbSet<Loop_NM1_837> Loop_NM1_837 { get; set; }
        public DbSet<Loop_NM1_837_2> Loop_NM1_837_2 { get; set; }
        public DbSet<Loop_NM1_837_3> Loop_NM1_837_3 { get; set; }
        public DbSet<Loop_NM1_837_4> Loop_NM1_837_4 { get; set; }
        public DbSet<Loop_PAT_837> Loop_PAT_837 { get; set; }
        public DbSet<Loop_PRV_837> Loop_PRV_837 { get; set; }
        public DbSet<Loop_SBR_837> Loop_SBR_837 { get; set; }
        public DbSet<Loop_SBR_837_2> Loop_SBR_837_2 { get; set; }
        public DbSet<TS837> TS837 { get; set; }
        public DbSet<Loop_ENE_838> Loop_ENE_838 { get; set; }
        public DbSet<Loop_LS_838> Loop_LS_838 { get; set; }
        public DbSet<Loop_LX_838> Loop_LX_838 { get; set; }
        public DbSet<Loop_N1_838> Loop_N1_838 { get; set; }
        public DbSet<Loop_N1_838_2> Loop_N1_838_2 { get; set; }
        public DbSet<Loop_PAM_838> Loop_PAM_838 { get; set; }
        public DbSet<Loop_PLA_838> Loop_PLA_838 { get; set; }
        public DbSet<Loop_SPR_838> Loop_SPR_838 { get; set; }
        public DbSet<Loop_TPD_838> Loop_TPD_838 { get; set; }
        public DbSet<Loop_TUD_838> Loop_TUD_838 { get; set; }
        public DbSet<Loop_TXN_838> Loop_TXN_838 { get; set; }
        public DbSet<TS838> TS838 { get; set; }
        public DbSet<Loop_BSD_839> Loop_BSD_839 { get; set; }
        public DbSet<Loop_CFT_839> Loop_CFT_839 { get; set; }
        public DbSet<Loop_N1_839> Loop_N1_839 { get; set; }
        public DbSet<TS839> TS839 { get; set; }
        public DbSet<Loop_LDT_840> Loop_LDT_840 { get; set; }
        public DbSet<Loop_N1_840> Loop_N1_840 { get; set; }
        public DbSet<Loop_N1_840_2> Loop_N1_840_2 { get; set; }
        public DbSet<Loop_N9_840> Loop_N9_840 { get; set; }
        public DbSet<Loop_PID_840> Loop_PID_840 { get; set; }
        public DbSet<Loop_PO1_840> Loop_PO1_840 { get; set; }
        public DbSet<Loop_SLN_840> Loop_SLN_840 { get; set; }
        public DbSet<TS840> TS840 { get; set; }
        public DbSet<Loop_CID_841> Loop_CID_841 { get; set; }
        public DbSet<Loop_CID_841_2> Loop_CID_841_2 { get; set; }
        public DbSet<Loop_CSF_841> Loop_CSF_841 { get; set; }
        public DbSet<Loop_EFI_841> Loop_EFI_841 { get; set; }
        public DbSet<Loop_HL_841> Loop_HL_841 { get; set; }
        public DbSet<Loop_LS_841> Loop_LS_841 { get; set; }
        public DbSet<Loop_LX_841> Loop_LX_841 { get; set; }
        public DbSet<Loop_MEA_841> Loop_MEA_841 { get; set; }
        public DbSet<Loop_N1_841> Loop_N1_841 { get; set; }
        public DbSet<Loop_PID_841> Loop_PID_841 { get; set; }
        public DbSet<Loop_PKG_841> Loop_PKG_841 { get; set; }
        public DbSet<Loop_REF_841> Loop_REF_841 { get; set; }
        public DbSet<Loop_SPI_841> Loop_SPI_841 { get; set; }
        public DbSet<Loop_SPI_841_2> Loop_SPI_841_2 { get; set; }
        public DbSet<Loop_STA_841> Loop_STA_841 { get; set; }
        public DbSet<TS841> TS841 { get; set; }
        public DbSet<Loop_HL_842> Loop_HL_842 { get; set; }
        public DbSet<Loop_LM_842> Loop_LM_842 { get; set; }
        public DbSet<Loop_MEA_842> Loop_MEA_842 { get; set; }
        public DbSet<Loop_N1_842> Loop_N1_842 { get; set; }
        public DbSet<Loop_NCA_842> Loop_NCA_842 { get; set; }
        public DbSet<Loop_NCD_842> Loop_NCD_842 { get; set; }
        public DbSet<Loop_PWK_842> Loop_PWK_842 { get; set; }
        public DbSet<Loop_SPS_842> Loop_SPS_842 { get; set; }
        public DbSet<Loop_STA_842> Loop_STA_842 { get; set; }
        public DbSet<TS842> TS842 { get; set; }
        public DbSet<Loop_CST_843> Loop_CST_843 { get; set; }
        public DbSet<Loop_N1_843> Loop_N1_843 { get; set; }
        public DbSet<Loop_N1_843_2> Loop_N1_843_2 { get; set; }
        public DbSet<Loop_N9_843> Loop_N9_843 { get; set; }
        public DbSet<Loop_PID_843> Loop_PID_843 { get; set; }
        public DbSet<Loop_PO1_843> Loop_PO1_843 { get; set; }
        public DbSet<Loop_SLN_843> Loop_SLN_843 { get; set; }
        public DbSet<TS843> TS843 { get; set; }
        public DbSet<Loop_CON_844> Loop_CON_844 { get; set; }
        public DbSet<Loop_N1_844> Loop_N1_844 { get; set; }
        public DbSet<Loop_PAD_844> Loop_PAD_844 { get; set; }
        public DbSet<TS844> TS844 { get; set; }
        public DbSet<Loop_CON_845> Loop_CON_845 { get; set; }
        public DbSet<Loop_CTP_845> Loop_CTP_845 { get; set; }
        public DbSet<Loop_LIN_845> Loop_LIN_845 { get; set; }
        public DbSet<Loop_N1_845> Loop_N1_845 { get; set; }
        public DbSet<Loop_N1_845_2> Loop_N1_845_2 { get; set; }
        public DbSet<Loop_N1_845_3> Loop_N1_845_3 { get; set; }
        public DbSet<Loop_PAD_845> Loop_PAD_845 { get; set; }
        public DbSet<TS845> TS845 { get; set; }
        public DbSet<Loop_LIN_846> Loop_LIN_846 { get; set; }
        public DbSet<Loop_LM_846> Loop_LM_846 { get; set; }
        public DbSet<Loop_LS_846> Loop_LS_846 { get; set; }
        public DbSet<Loop_MAN_846> Loop_MAN_846 { get; set; }
        public DbSet<Loop_N1_846> Loop_N1_846 { get; set; }
        public DbSet<Loop_QTY_846> Loop_QTY_846 { get; set; }
        public DbSet<Loop_REF_846> Loop_REF_846 { get; set; }
        public DbSet<Loop_SCH_846> Loop_SCH_846 { get; set; }
        public DbSet<Loop_SLN_846> Loop_SLN_846 { get; set; }
        public DbSet<TS846> TS846 { get; set; }
        public DbSet<Loop_HL_847> Loop_HL_847 { get; set; }
        public DbSet<Loop_N1_847> Loop_N1_847 { get; set; }
        public DbSet<Loop_N1_847_2> Loop_N1_847_2 { get; set; }
        public DbSet<TS847> TS847 { get; set; }
        public DbSet<Loop_CID_848> Loop_CID_848 { get; set; }
        public DbSet<Loop_LIN_848> Loop_LIN_848 { get; set; }
        public DbSet<Loop_LX_848> Loop_LX_848 { get; set; }
        public DbSet<Loop_MSS_848> Loop_MSS_848 { get; set; }
        public DbSet<Loop_N1_848> Loop_N1_848 { get; set; }
        public DbSet<Loop_SD1_848> Loop_SD1_848 { get; set; }
        public DbSet<TS848> TS848 { get; set; }
        public DbSet<Loop_CON_849> Loop_CON_849 { get; set; }
        public DbSet<Loop_N1_849> Loop_N1_849 { get; set; }
        public DbSet<Loop_PAD_849> Loop_PAD_849 { get; set; }
        public DbSet<TS849> TS849 { get; set; }
        public DbSet<Loop_N1_850> Loop_N1_850 { get; set; }
        public DbSet<Loop_N1_850_2> Loop_N1_850_2 { get; set; }
        public DbSet<Loop_N1_850_3> Loop_N1_850_3 { get; set; }
        public DbSet<Loop_N9_850> Loop_N9_850 { get; set; }
        public DbSet<Loop_N9_850_2> Loop_N9_850_2 { get; set; }
        public DbSet<Loop_PID_850> Loop_PID_850 { get; set; }
        public DbSet<Loop_PKG_850> Loop_PKG_850 { get; set; }
        public DbSet<Loop_PO1_850> Loop_PO1_850 { get; set; }
        public DbSet<Loop_SLN_850> Loop_SLN_850 { get; set; }
        public DbSet<TS850> TS850 { get; set; }
        public DbSet<Loop_LS1_851> Loop_LS1_851 { get; set; }
        public DbSet<Loop_N1_851> Loop_N1_851 { get; set; }
        public DbSet<TS851> TS851 { get; set; }
        public DbSet<Loop_LIN_852> Loop_LIN_852 { get; set; }
        public DbSet<Loop_N1_852> Loop_N1_852 { get; set; }
        public DbSet<Loop_ZA_852> Loop_ZA_852 { get; set; }
        public DbSet<TS852> TS852 { get; set; }
        public DbSet<Loop_N1_853> Loop_N1_853 { get; set; }
        public DbSet<Loop_TD5_853> Loop_TD5_853 { get; set; }
        public DbSet<TS853> TS853 { get; set; }
        public DbSet<Loop_LS_854> Loop_LS_854 { get; set; }
        public DbSet<Loop_LX_854> Loop_LX_854 { get; set; }
        public DbSet<Loop_N1_854> Loop_N1_854 { get; set; }
        public DbSet<Loop_N1_854_2> Loop_N1_854_2 { get; set; }
        public DbSet<Loop_N1_854_3> Loop_N1_854_3 { get; set; }
        public DbSet<Loop_Q8_854> Loop_Q8_854 { get; set; }
        public DbSet<TS854> TS854 { get; set; }
        public DbSet<Loop_ACK_855> Loop_ACK_855 { get; set; }
        public DbSet<Loop_N1_855> Loop_N1_855 { get; set; }
        public DbSet<Loop_N1_855_2> Loop_N1_855_2 { get; set; }
        public DbSet<Loop_N1_855_3> Loop_N1_855_3 { get; set; }
        public DbSet<Loop_N9_855> Loop_N9_855 { get; set; }
        public DbSet<Loop_PID_855> Loop_PID_855 { get; set; }
        public DbSet<Loop_PKG_855> Loop_PKG_855 { get; set; }
        public DbSet<Loop_PO1_855> Loop_PO1_855 { get; set; }
        public DbSet<Loop_SLN_855> Loop_SLN_855 { get; set; }
        public DbSet<TS855> TS855 { get; set; }
        public DbSet<Loop_CLD_856> Loop_CLD_856 { get; set; }
        public DbSet<Loop_HL_856> Loop_HL_856 { get; set; }
        public DbSet<Loop_LM_856> Loop_LM_856 { get; set; }
        public DbSet<Loop_N1_856> Loop_N1_856 { get; set; }
        public DbSet<TS856> TS856 { get; set; }
        public DbSet<Loop_G05_857> Loop_G05_857 { get; set; }
        public DbSet<Loop_HL_857> Loop_HL_857 { get; set; }
        public DbSet<Loop_IT1_857> Loop_IT1_857 { get; set; }
        public DbSet<Loop_LX_857> Loop_LX_857 { get; set; }
        public DbSet<Loop_N1_857> Loop_N1_857 { get; set; }
        public DbSet<Loop_PAL_857> Loop_PAL_857 { get; set; }
        public DbSet<Loop_PID_857> Loop_PID_857 { get; set; }
        public DbSet<Loop_SAC_857> Loop_SAC_857 { get; set; }
        public DbSet<Loop_SLN_857> Loop_SLN_857 { get; set; }
        public DbSet<Loop_TDS_857> Loop_TDS_857 { get; set; }
        public DbSet<TS857> TS857 { get; set; }
        public DbSet<Loop_L0_858> Loop_L0_858 { get; set; }
        public DbSet<Loop_LH1_858> Loop_LH1_858 { get; set; }
        public DbSet<Loop_LX_858> Loop_LX_858 { get; set; }
        public DbSet<Loop_N1_858> Loop_N1_858 { get; set; }
        public DbSet<Loop_N7_858> Loop_N7_858 { get; set; }
        public DbSet<Loop_S5_858> Loop_S5_858 { get; set; }
        public DbSet<TS858> TS858 { get; set; }
        public DbSet<Loop_H1_859> Loop_H1_859 { get; set; }
        public DbSet<Loop_L0_859> Loop_L0_859 { get; set; }
        public DbSet<Loop_LX_859> Loop_LX_859 { get; set; }
        public DbSet<Loop_N1_859> Loop_N1_859 { get; set; }
        public DbSet<Loop_N7_859> Loop_N7_859 { get; set; }
        public DbSet<Loop_S5_859> Loop_S5_859 { get; set; }
        public DbSet<TS859> TS859 { get; set; }
        public DbSet<Loop_N1_860> Loop_N1_860 { get; set; }
        public DbSet<Loop_N1_860_2> Loop_N1_860_2 { get; set; }
        public DbSet<Loop_N1_860_3> Loop_N1_860_3 { get; set; }
        public DbSet<Loop_N9_860> Loop_N9_860 { get; set; }
        public DbSet<Loop_PID_860> Loop_PID_860 { get; set; }
        public DbSet<Loop_POC_860> Loop_POC_860 { get; set; }
        public DbSet<Loop_SLN_860> Loop_SLN_860 { get; set; }
        public DbSet<TS860> TS860 { get; set; }
        public DbSet<Loop_LM_861> Loop_LM_861 { get; set; }
        public DbSet<Loop_N1_861> Loop_N1_861 { get; set; }
        public DbSet<Loop_RCD_861> Loop_RCD_861 { get; set; }
        public DbSet<Loop_SLN_861> Loop_SLN_861 { get; set; }
        public DbSet<TS861> TS861 { get; set; }
        public DbSet<Loop_FST_862> Loop_FST_862 { get; set; }
        public DbSet<Loop_JIT_862> Loop_JIT_862 { get; set; }
        public DbSet<Loop_LIN_862> Loop_LIN_862 { get; set; }
        public DbSet<Loop_N1_862> Loop_N1_862 { get; set; }
        public DbSet<Loop_SHP_862> Loop_SHP_862 { get; set; }
        public DbSet<TS862> TS862 { get; set; }
        public DbSet<Loop_CID_863> Loop_CID_863 { get; set; }
        public DbSet<Loop_LIN_863> Loop_LIN_863 { get; set; }
        public DbSet<Loop_LM_863> Loop_LM_863 { get; set; }
        public DbSet<Loop_MEA_863> Loop_MEA_863 { get; set; }
        public DbSet<Loop_N1_863> Loop_N1_863 { get; set; }
        public DbSet<Loop_N1_863_2> Loop_N1_863_2 { get; set; }
        public DbSet<Loop_STA_863> Loop_STA_863 { get; set; }
        public DbSet<Loop_TMD_863> Loop_TMD_863 { get; set; }
        public DbSet<Loop_TSP_863> Loop_TSP_863 { get; set; }
        public DbSet<TS863> TS863 { get; set; }
        public DbSet<Loop_MIT_864> Loop_MIT_864 { get; set; }
        public DbSet<Loop_N1_864> Loop_N1_864 { get; set; }
        public DbSet<TS864> TS864 { get; set; }
        public DbSet<Loop_ACK_865> Loop_ACK_865 { get; set; }
        public DbSet<Loop_N1_865> Loop_N1_865 { get; set; }
        public DbSet<Loop_N1_865_2> Loop_N1_865_2 { get; set; }
        public DbSet<Loop_N1_865_3> Loop_N1_865_3 { get; set; }
        public DbSet<Loop_N9_865> Loop_N9_865 { get; set; }
        public DbSet<Loop_PID_865> Loop_PID_865 { get; set; }
        public DbSet<Loop_POC_865> Loop_POC_865 { get; set; }
        public DbSet<Loop_SLN_865> Loop_SLN_865 { get; set; }
        public DbSet<TS865> TS865 { get; set; }
        public DbSet<Loop_DTM_866> Loop_DTM_866 { get; set; }
        public DbSet<Loop_LIN_866> Loop_LIN_866 { get; set; }
        public DbSet<Loop_N1_866> Loop_N1_866 { get; set; }
        public DbSet<Loop_PID_866> Loop_PID_866 { get; set; }
        public DbSet<Loop_SLN_866> Loop_SLN_866 { get; set; }
        public DbSet<TS866> TS866 { get; set; }
        public DbSet<Loop_CTT_867> Loop_CTT_867 { get; set; }
        public DbSet<Loop_LM_867> Loop_LM_867 { get; set; }
        public DbSet<Loop_LM_867_2> Loop_LM_867_2 { get; set; }
        public DbSet<Loop_LX_867> Loop_LX_867 { get; set; }
        public DbSet<Loop_N1_867> Loop_N1_867 { get; set; }
        public DbSet<Loop_PTD_867> Loop_PTD_867 { get; set; }
        public DbSet<Loop_QTY_867> Loop_QTY_867 { get; set; }
        public DbSet<TS867> TS867 { get; set; }
        public DbSet<Loop_E10_868> Loop_E10_868 { get; set; }
        public DbSet<Loop_E20_868> Loop_E20_868 { get; set; }
        public DbSet<Loop_E24_868> Loop_E24_868 { get; set; }
        public DbSet<Loop_E30_868> Loop_E30_868 { get; set; }
        public DbSet<Loop_E34_868> Loop_E34_868 { get; set; }
        public DbSet<Loop_E40_868> Loop_E40_868 { get; set; }
        public DbSet<TS868> TS868 { get; set; }
        public DbSet<Loop_HL_869> Loop_HL_869 { get; set; }
        public DbSet<Loop_N1_869> Loop_N1_869 { get; set; }
        public DbSet<TS869> TS869 { get; set; }
        public DbSet<Loop_HL_870> Loop_HL_870 { get; set; }
        public DbSet<Loop_ISR_870> Loop_ISR_870 { get; set; }
        public DbSet<Loop_ISR_870_2> Loop_ISR_870_2 { get; set; }
        public DbSet<Loop_LM_870> Loop_LM_870 { get; set; }
        public DbSet<Loop_LX_870> Loop_LX_870 { get; set; }
        public DbSet<Loop_N1_870> Loop_N1_870 { get; set; }
        public DbSet<Loop_N1_870_2> Loop_N1_870_2 { get; set; }
        public DbSet<Loop_PO1_870> Loop_PO1_870 { get; set; }
        public DbSet<TS870> TS870 { get; set; }
        public DbSet<Loop_BUY_872> Loop_BUY_872 { get; set; }
        public DbSet<Loop_IN1_872> Loop_IN1_872 { get; set; }
        public DbSet<Loop_LX_872> Loop_LX_872 { get; set; }
        public DbSet<Loop_MCD_872> Loop_MCD_872 { get; set; }
        public DbSet<Loop_MII_872> Loop_MII_872 { get; set; }
        public DbSet<Loop_N1_872> Loop_N1_872 { get; set; }
        public DbSet<Loop_N4_872> Loop_N4_872 { get; set; }
        public DbSet<Loop_NX1_872> Loop_NX1_872 { get; set; }
        public DbSet<Loop_PAS_872> Loop_PAS_872 { get; set; }
        public DbSet<Loop_PRJ_872> Loop_PRJ_872 { get; set; }
        public DbSet<Loop_PWK_872> Loop_PWK_872 { get; set; }
        public DbSet<Loop_REA_872> Loop_REA_872 { get; set; }
        public DbSet<TS872> TS872 { get; set; }
        public DbSet<Loop_G68_875> Loop_G68_875 { get; set; }
        public DbSet<Loop_G72_875> Loop_G72_875 { get; set; }
        public DbSet<Loop_N1_875> Loop_N1_875 { get; set; }
        public DbSet<TS875> TS875 { get; set; }
        public DbSet<Loop_G68_876> Loop_G68_876 { get; set; }
        public DbSet<Loop_G72_876> Loop_G72_876 { get; set; }
        public DbSet<Loop_N1_876> Loop_N1_876 { get; set; }
        public DbSet<TS876> TS876 { get; set; }
        public DbSet<Loop_G21_878> Loop_G21_878 { get; set; }
        public DbSet<Loop_N1_878> Loop_N1_878 { get; set; }
        public DbSet<Loop_N1_878_2> Loop_N1_878_2 { get; set; }
        public DbSet<TS878> TS878 { get; set; }
        public DbSet<Loop_G28_879> Loop_G28_879 { get; set; }
        public DbSet<Loop_N1_879> Loop_N1_879 { get; set; }
        public DbSet<TS879> TS879 { get; set; }
        public DbSet<Loop_G17_880> Loop_G17_880 { get; set; }
        public DbSet<Loop_G72_880> Loop_G72_880 { get; set; }
        public DbSet<Loop_N1_880> Loop_N1_880 { get; set; }
        public DbSet<TS880> TS880 { get; set; }
        public DbSet<Loop_G48_882> Loop_G48_882 { get; set; }
        public DbSet<Loop_G72_882> Loop_G72_882 { get; set; }
        public DbSet<Loop_N1_882> Loop_N1_882 { get; set; }
        public DbSet<TS882> TS882 { get; set; }
        public DbSet<Loop_G39_888> Loop_G39_888 { get; set; }
        public DbSet<Loop_G53_888> Loop_G53_888 { get; set; }
        public DbSet<Loop_G55_888> Loop_G55_888 { get; set; }
        public DbSet<Loop_LM_888> Loop_LM_888 { get; set; }
        public DbSet<Loop_N1_888> Loop_N1_888 { get; set; }
        public DbSet<Loop_N1_888_2> Loop_N1_888_2 { get; set; }
        public DbSet<TS888> TS888 { get; set; }
        public DbSet<Loop_G45_889> Loop_G45_889 { get; set; }
        public DbSet<Loop_G94_889> Loop_G94_889 { get; set; }
        public DbSet<Loop_LX_889> Loop_LX_889 { get; set; }
        public DbSet<Loop_N1_889> Loop_N1_889 { get; set; }
        public DbSet<TS889> TS889 { get; set; }
        public DbSet<Loop_N1_893> Loop_N1_893 { get; set; }
        public DbSet<TS893> TS893 { get; set; }
        public DbSet<Loop_G83_894> Loop_G83_894 { get; set; }
        public DbSet<Loop_LS_894> Loop_LS_894 { get; set; }
        public DbSet<TS894> TS894 { get; set; }
        public DbSet<Loop_G89_895> Loop_G89_895 { get; set; }
        public DbSet<Loop_LS_895> Loop_LS_895 { get; set; }
        public DbSet<TS895> TS895 { get; set; }
        public DbSet<Loop_ID1_896> Loop_ID1_896 { get; set; }
        public DbSet<Loop_N1_896> Loop_N1_896 { get; set; }
        public DbSet<TS896> TS896 { get; set; }
        public DbSet<Loop_F02_920> Loop_F02_920 { get; set; }
        public DbSet<Loop_F09_920> Loop_F09_920 { get; set; }
        public DbSet<Loop_N1_920> Loop_N1_920 { get; set; }
        public DbSet<TS920> TS920 { get; set; }
        public DbSet<TS924> TS924 { get; set; }
        public DbSet<Loop_F10_925> Loop_F10_925 { get; set; }
        public DbSet<TS925> TS925 { get; set; }
        public DbSet<Loop_F11_926> Loop_F11_926 { get; set; }
        public DbSet<TS926> TS926 { get; set; }
        public DbSet<Loop_VC_928> Loop_VC_928 { get; set; }
        public DbSet<TS928> TS928 { get; set; }
        public DbSet<Loop_LM_940> Loop_LM_940 { get; set; }
        public DbSet<Loop_LX_940> Loop_LX_940 { get; set; }
        public DbSet<Loop_N1_940> Loop_N1_940 { get; set; }
        public DbSet<Loop_W01_940> Loop_W01_940 { get; set; }
        public DbSet<TS940> TS940 { get; set; }
        public DbSet<Loop_N1_943> Loop_N1_943 { get; set; }
        public DbSet<Loop_W04_943> Loop_W04_943 { get; set; }
        public DbSet<TS943> TS943 { get; set; }
        public DbSet<Loop_N1_944> Loop_N1_944 { get; set; }
        public DbSet<Loop_W07_944> Loop_W07_944 { get; set; }
        public DbSet<Loop_W13_944> Loop_W13_944 { get; set; }
        public DbSet<TS944> TS944 { get; set; }
        public DbSet<Loop_LM_945> Loop_LM_945 { get; set; }
        public DbSet<Loop_LX_945> Loop_LX_945 { get; set; }
        public DbSet<Loop_N1_945> Loop_N1_945 { get; set; }
        public DbSet<Loop_W12_945> Loop_W12_945 { get; set; }
        public DbSet<TS945> TS945 { get; set; }
        public DbSet<Loop_LM_947> Loop_LM_947 { get; set; }
        public DbSet<Loop_LX_947> Loop_LX_947 { get; set; }
        public DbSet<Loop_N1_947> Loop_N1_947 { get; set; }
        public DbSet<Loop_N1_947_2> Loop_N1_947_2 { get; set; }
        public DbSet<Loop_W19_947> Loop_W19_947 { get; set; }
        public DbSet<TS947> TS947 { get; set; }
        public DbSet<TS980> TS980 { get; set; }
        public DbSet<Loop_S5_990> Loop_S5_990 { get; set; }
        public DbSet<TS990> TS990 { get; set; }
        public DbSet<TS996> TS996 { get; set; }
        public DbSet<Loop_AK2_997> Loop_AK2_997 { get; set; }
        public DbSet<Loop_AK3_997> Loop_AK3_997 { get; set; }
        public DbSet<TS997> TS997 { get; set; }
        public DbSet<TS998> TS998 { get; set; }
    }
}
