namespace EdiFabric.Templates.X12003010
{
    using System.Data.Entity;
    using System.Linq;
    
    
    public class X12Context : DbContext
    {
        
        public DbSet<AAA> AAA { get; set; }
        public DbSet<ACK> ACK { get; set; }
        public DbSet<ACT> ACT { get; set; }
        public DbSet<ADJ> ADJ { get; set; }
        public DbSet<AK1> AK1 { get; set; }
        public DbSet<AK2> AK2 { get; set; }
        public DbSet<AK3> AK3 { get; set; }
        public DbSet<AK4> AK4 { get; set; }
        public DbSet<AK5> AK5 { get; set; }
        public DbSet<AK9> AK9 { get; set; }
        public DbSet<AMT> AMT { get; set; }
        public DbSet<ATH> ATH { get; set; }
        public DbSet<AVA> AVA { get; set; }
        public DbSet<B3> B3 { get; set; }
        public DbSet<B3A> B3A { get; set; }
        public DbSet<BAA> BAA { get; set; }
        public DbSet<BAK> BAK { get; set; }
        public DbSet<BAL> BAL { get; set; }
        public DbSet<BAT> BAT { get; set; }
        public DbSet<BCA> BCA { get; set; }
        public DbSet<BCH> BCH { get; set; }
        public DbSet<BCO> BCO { get; set; }
        public DbSet<BCT> BCT { get; set; }
        public DbSet<BEG> BEG { get; set; }
        public DbSet<BFR> BFR { get; set; }
        public DbSet<BGN> BGN { get; set; }
        public DbSet<BIA> BIA { get; set; }
        public DbSet<BIG> BIG { get; set; }
        public DbSet<BIN> BIN { get; set; }
        public DbSet<BMG> BMG { get; set; }
        public DbSet<BNR> BNR { get; set; }
        public DbSet<BNX> BNX { get; set; }
        public DbSet<BOS> BOS { get; set; }
        public DbSet<BPA> BPA { get; set; }
        public DbSet<BPS> BPS { get; set; }
        public DbSet<BPT> BPT { get; set; }
        public DbSet<BQR> BQR { get; set; }
        public DbSet<BQT> BQT { get; set; }
        public DbSet<BRA> BRA { get; set; }
        public DbSet<BRC> BRC { get; set; }
        public DbSet<BSI> BSI { get; set; }
        public DbSet<BSN> BSN { get; set; }
        public DbSet<BSR> BSR { get; set; }
        public DbSet<BSS> BSS { get; set; }
        public DbSet<BTI> BTI { get; set; }
        public DbSet<BTR> BTR { get; set; }
        public DbSet<BX> BX { get; set; }
        public DbSet<C3> C3 { get; set; }
        public DbSet<CAD> CAD { get; set; }
        public DbSet<CID> CID { get; set; }
        public DbSet<CLD> CLD { get; set; }
        public DbSet<CM> CM { get; set; }
        public DbSet<CON> CON { get; set; }
        public DbSet<CSH> CSH { get; set; }
        public DbSet<CST> CST { get; set; }
        public DbSet<CTB> CTB { get; set; }
        public DbSet<CTP> CTP { get; set; }
        public DbSet<CTT> CTT { get; set; }
        public DbSet<CUR> CUR { get; set; }
        public DbSet<D9> D9 { get; set; }
        public DbSet<DAI> DAI { get; set; }
        public DbSet<DDI> DDI { get; set; }
        public DbSet<DEP> DEP { get; set; }
        public DbSet<DIS> DIS { get; set; }
        public DbSet<DMI> DMI { get; set; }
        public DbSet<DTM> DTM { get; set; }
        public DbSet<E01> E01 { get; set; }
        public DbSet<E03> E03 { get; set; }
        public DbSet<E1> E1 { get; set; }
        public DbSet<E10> E10 { get; set; }
        public DbSet<E12> E12 { get; set; }
        public DbSet<E14> E14 { get; set; }
        public DbSet<E20> E20 { get; set; }
        public DbSet<E22> E22 { get; set; }
        public DbSet<E24> E24 { get; set; }
        public DbSet<E26> E26 { get; set; }
        public DbSet<E30> E30 { get; set; }
        public DbSet<E34> E34 { get; set; }
        public DbSet<E4> E4 { get; set; }
        public DbSet<E40> E40 { get; set; }
        public DbSet<E5> E5 { get; set; }
        public DbSet<EFI> EFI { get; set; }
        public DbSet<ETD> ETD { get; set; }
        public DbSet<F9> F9 { get; set; }
        public DbSet<FIR> FIR { get; set; }
        public DbSet<FOB> FOB { get; set; }
        public DbSet<FST> FST { get; set; }
        public DbSet<G4> G4 { get; set; }
        public DbSet<G62> G62 { get; set; }
        public DbSet<GA> GA { get; set; }
        public DbSet<GOV> GOV { get; set; }
        public DbSet<H1> H1 { get; set; }
        public DbSet<H2> H2 { get; set; }
        public DbSet<H3> H3 { get; set; }
        public DbSet<H6> H6 { get; set; }
        public DbSet<HL> HL { get; set; }
        public DbSet<IC> IC { get; set; }
        public DbSet<ISR> ISR { get; set; }
        public DbSet<ISS> ISS { get; set; }
        public DbSet<IT1> IT1 { get; set; }
        public DbSet<IT3> IT3 { get; set; }
        public DbSet<IT8> IT8 { get; set; }
        public DbSet<ITA> ITA { get; set; }
        public DbSet<ITD> ITD { get; set; }
        public DbSet<JID> JID { get; set; }
        public DbSet<JIL> JIL { get; set; }
        public DbSet<JIT> JIT { get; set; }
        public DbSet<L0> L0 { get; set; }
        public DbSet<L1> L1 { get; set; }
        public DbSet<L3> L3 { get; set; }
        public DbSet<L5> L5 { get; set; }
        public DbSet<L7> L7 { get; set; }
        public DbSet<L8> L8 { get; set; }
        public DbSet<LDT> LDT { get; set; }
        public DbSet<LE> LE { get; set; }
        public DbSet<LH> LH { get; set; }
        public DbSet<LH1> LH1 { get; set; }
        public DbSet<LH2> LH2 { get; set; }
        public DbSet<LH3> LH3 { get; set; }
        public DbSet<LH4> LH4 { get; set; }
        public DbSet<LH5> LH5 { get; set; }
        public DbSet<LH6> LH6 { get; set; }
        public DbSet<LHE> LHE { get; set; }
        public DbSet<LHR> LHR { get; set; }
        public DbSet<LIN> LIN { get; set; }
        public DbSet<LS> LS { get; set; }
        public DbSet<LX> LX { get; set; }
        public DbSet<M1> M1 { get; set; }
        public DbSet<M2> M2 { get; set; }
        public DbSet<M3> M3 { get; set; }
        public DbSet<M7> M7 { get; set; }
        public DbSet<MAN> MAN { get; set; }
        public DbSet<MEA> MEA { get; set; }
        public DbSet<MIT> MIT { get; set; }
        public DbSet<MSG> MSG { get; set; }
        public DbSet<N1> N1 { get; set; }
        public DbSet<N2> N2 { get; set; }
        public DbSet<N3> N3 { get; set; }
        public DbSet<N4> N4 { get; set; }
        public DbSet<N5> N5 { get; set; }
        public DbSet<N7> N7 { get; set; }
        public DbSet<N8> N8 { get; set; }
        public DbSet<N9> N9 { get; set; }
        public DbSet<NA> NA { get; set; }
        public DbSet<NCA> NCA { get; set; }
        public DbSet<NCD> NCD { get; set; }
        public DbSet<NTE> NTE { get; set; }
        public DbSet<OTI> OTI { get; set; }
        public DbSet<P1> P1 { get; set; }
        public DbSet<P2> P2 { get; set; }
        public DbSet<PAD> PAD { get; set; }
        public DbSet<PCR> PCR { get; set; }
        public DbSet<PER> PER { get; set; }
        public DbSet<PID> PID { get; set; }
        public DbSet<PKG> PKG { get; set; }
        public DbSet<PO1> PO1 { get; set; }
        public DbSet<PO3> PO3 { get; set; }
        public DbSet<PO4> PO4 { get; set; }
        public DbSet<POC> POC { get; set; }
        public DbSet<POD> POD { get; set; }
        public DbSet<PRF> PRF { get; set; }
        public DbSet<PRS> PRS { get; set; }
        public DbSet<PS> PS { get; set; }
        public DbSet<PSA> PSA { get; set; }
        public DbSet<PSD> PSD { get; set; }
        public DbSet<PTD> PTD { get; set; }
        public DbSet<PWK> PWK { get; set; }
        public DbSet<QTY> QTY { get; set; }
        public DbSet<R1> R1 { get; set; }
        public DbSet<R2> R2 { get; set; }
        public DbSet<R3> R3 { get; set; }
        public DbSet<R4> R4 { get; set; }
        public DbSet<R9> R9 { get; set; }
        public DbSet<RCD> RCD { get; set; }
        public DbSet<RDT> RDT { get; set; }
        public DbSet<REF> REF { get; set; }
        public DbSet<RIC> RIC { get; set; }
        public DbSet<RMT> RMT { get; set; }
        public DbSet<RRA> RRA { get; set; }
        public DbSet<RTE> RTE { get; set; }
        public DbSet<S5> S5 { get; set; }
        public DbSet<SCH> SCH { get; set; }
        public DbSet<SDP> SDP { get; set; }
        public DbSet<SDQ> SDQ { get; set; }
        public DbSet<SER> SER { get; set; }
        public DbSet<SHP> SHP { get; set; }
        public DbSet<SL1> SL1 { get; set; }
        public DbSet<SLN> SLN { get; set; }
        public DbSet<SN1> SN1 { get; set; }
        public DbSet<SPI> SPI { get; set; }
        public DbSet<SPS> SPS { get; set; }
        public DbSet<SSS> SSS { get; set; }
        public DbSet<STA> STA { get; set; }
        public DbSet<TAX> TAX { get; set; }
        public DbSet<TD1> TD1 { get; set; }
        public DbSet<TD3> TD3 { get; set; }
        public DbSet<TD4> TD4 { get; set; }
        public DbSet<TD5> TD5 { get; set; }
        public DbSet<TDS> TDS { get; set; }
        public DbSet<TED> TED { get; set; }
        public DbSet<TFS> TFS { get; set; }
        public DbSet<TIA> TIA { get; set; }
        public DbSet<TMD> TMD { get; set; }
        public DbSet<TRN> TRN { get; set; }
        public DbSet<TXI> TXI { get; set; }
        public DbSet<UIT> UIT { get; set; }
        public DbSet<V9> V9 { get; set; }
        public DbSet<VC> VC { get; set; }
        public DbSet<X1> X1 { get; set; }
        public DbSet<X2> X2 { get; set; }
        public DbSet<X7> X7 { get; set; }
        public DbSet<XH> XH { get; set; }
        public DbSet<XPO> XPO { get; set; }
        public DbSet<XQ> XQ { get; set; }
        public DbSet<Y6> Y6 { get; set; }
        public DbSet<Y7> Y7 { get; set; }
        public DbSet<ZA> ZA { get; set; }
        public DbSet<ZC1> ZC1 { get; set; }
        public DbSet<Loop_IT1_810> Loop_IT1_810 { get; set; }
        public DbSet<Loop_ITA_810> Loop_ITA_810 { get; set; }
        public DbSet<Loop_N1_810> Loop_N1_810 { get; set; }
        public DbSet<Loop_PID_810> Loop_PID_810 { get; set; }
        public DbSet<Loop_SLN_810> Loop_SLN_810 { get; set; }
        public DbSet<TS810> TS810 { get; set; }
        public DbSet<Loop_JID_819> Loop_JID_819 { get; set; }
        public DbSet<Loop_JIL_819> Loop_JIL_819 { get; set; }
        public DbSet<Loop_N1_819> Loop_N1_819 { get; set; }
        public DbSet<Loop_PSA_819> Loop_PSA_819 { get; set; }
        public DbSet<TS819> TS819 { get; set; }
        public DbSet<Loop_LS_820> Loop_LS_820 { get; set; }
        public DbSet<Loop_N1_820> Loop_N1_820 { get; set; }
        public DbSet<Loop_N1_820_2> Loop_N1_820_2 { get; set; }
        public DbSet<Loop_RMT_820> Loop_RMT_820 { get; set; }
        public DbSet<TS820> TS820 { get; set; }
        public DbSet<Loop_ACT_821> Loop_ACT_821 { get; set; }
        public DbSet<Loop_FIR_821> Loop_FIR_821 { get; set; }
        public DbSet<Loop_N1_821> Loop_N1_821 { get; set; }
        public DbSet<TS821> TS821 { get; set; }
        public DbSet<Loop_ACT_822> Loop_ACT_822 { get; set; }
        public DbSet<Loop_ADJ_822> Loop_ADJ_822 { get; set; }
        public DbSet<Loop_BAL_822> Loop_BAL_822 { get; set; }
        public DbSet<Loop_N1_822> Loop_N1_822 { get; set; }
        public DbSet<Loop_SER_822> Loop_SER_822 { get; set; }
        public DbSet<TS822> TS822 { get; set; }
        public DbSet<Loop_BAT_823> Loop_BAT_823 { get; set; }
        public DbSet<Loop_BPS_823> Loop_BPS_823 { get; set; }
        public DbSet<Loop_DEP_823> Loop_DEP_823 { get; set; }
        public DbSet<Loop_N1_823> Loop_N1_823 { get; set; }
        public DbSet<Loop_RMT_823> Loop_RMT_823 { get; set; }
        public DbSet<TS823> TS823 { get; set; }
        public DbSet<Loop_N1_824> Loop_N1_824 { get; set; }
        public DbSet<Loop_OTI_824> Loop_OTI_824 { get; set; }
        public DbSet<Loop_TED_824> Loop_TED_824 { get; set; }
        public DbSet<TS824> TS824 { get; set; }
        public DbSet<Loop_N1_826> Loop_N1_826 { get; set; }
        public DbSet<Loop_TFS_826> Loop_TFS_826 { get; set; }
        public DbSet<TS826> TS826 { get; set; }
        public DbSet<TS827> TS827 { get; set; }
        public DbSet<TS829> TS829 { get; set; }
        public DbSet<Loop_FST_830> Loop_FST_830 { get; set; }
        public DbSet<Loop_LIN_830> Loop_LIN_830 { get; set; }
        public DbSet<Loop_N1_830> Loop_N1_830 { get; set; }
        public DbSet<Loop_SDP_830> Loop_SDP_830 { get; set; }
        public DbSet<Loop_SHP_830> Loop_SHP_830 { get; set; }
        public DbSet<Loop_SLN_830> Loop_SLN_830 { get; set; }
        public DbSet<TS830> TS830 { get; set; }
        public DbSet<Loop_CTP_832> Loop_CTP_832 { get; set; }
        public DbSet<Loop_LIN_832> Loop_LIN_832 { get; set; }
        public DbSet<Loop_N1_832> Loop_N1_832 { get; set; }
        public DbSet<TS832> TS832 { get; set; }
        public DbSet<Loop_N1_836> Loop_N1_836 { get; set; }
        public DbSet<Loop_PO1_836> Loop_PO1_836 { get; set; }
        public DbSet<Loop_SLN_836> Loop_SLN_836 { get; set; }
        public DbSet<TS836> TS836 { get; set; }
        public DbSet<Loop_N1_840> Loop_N1_840 { get; set; }
        public DbSet<Loop_N9_840> Loop_N9_840 { get; set; }
        public DbSet<Loop_PID_840> Loop_PID_840 { get; set; }
        public DbSet<Loop_PO1_840> Loop_PO1_840 { get; set; }
        public DbSet<Loop_SLN_840> Loop_SLN_840 { get; set; }
        public DbSet<TS840> TS840 { get; set; }
        public DbSet<Loop_CID_841> Loop_CID_841 { get; set; }
        public DbSet<Loop_EFI_841> Loop_EFI_841 { get; set; }
        public DbSet<Loop_HL_841> Loop_HL_841 { get; set; }
        public DbSet<Loop_MEA_841> Loop_MEA_841 { get; set; }
        public DbSet<Loop_N1_841> Loop_N1_841 { get; set; }
        public DbSet<Loop_PID_841> Loop_PID_841 { get; set; }
        public DbSet<Loop_REF_841> Loop_REF_841 { get; set; }
        public DbSet<Loop_SPI_841> Loop_SPI_841 { get; set; }
        public DbSet<Loop_SPI_841_2> Loop_SPI_841_2 { get; set; }
        public DbSet<Loop_STA_841> Loop_STA_841 { get; set; }
        public DbSet<TS841> TS841 { get; set; }
        public DbSet<Loop_HL_842> Loop_HL_842 { get; set; }
        public DbSet<Loop_MEA_842> Loop_MEA_842 { get; set; }
        public DbSet<Loop_N1_842> Loop_N1_842 { get; set; }
        public DbSet<Loop_N1_842_2> Loop_N1_842_2 { get; set; }
        public DbSet<Loop_NCA_842> Loop_NCA_842 { get; set; }
        public DbSet<Loop_NCD_842> Loop_NCD_842 { get; set; }
        public DbSet<Loop_PWK_842> Loop_PWK_842 { get; set; }
        public DbSet<Loop_SPS_842> Loop_SPS_842 { get; set; }
        public DbSet<Loop_STA_842> Loop_STA_842 { get; set; }
        public DbSet<TS842> TS842 { get; set; }
        public DbSet<Loop_CST_843> Loop_CST_843 { get; set; }
        public DbSet<Loop_N1_843> Loop_N1_843 { get; set; }
        public DbSet<Loop_N9_843> Loop_N9_843 { get; set; }
        public DbSet<Loop_PID_843> Loop_PID_843 { get; set; }
        public DbSet<Loop_PO1_843> Loop_PO1_843 { get; set; }
        public DbSet<Loop_SLN_843> Loop_SLN_843 { get; set; }
        public DbSet<TS843> TS843 { get; set; }
        public DbSet<Loop_CON_844> Loop_CON_844 { get; set; }
        public DbSet<Loop_N1_844> Loop_N1_844 { get; set; }
        public DbSet<Loop_PAD_844> Loop_PAD_844 { get; set; }
        public DbSet<TS844> TS844 { get; set; }
        public DbSet<Loop_CON_845> Loop_CON_845 { get; set; }
        public DbSet<Loop_N1_845> Loop_N1_845 { get; set; }
        public DbSet<Loop_N1_845_2> Loop_N1_845_2 { get; set; }
        public DbSet<Loop_PAD_845> Loop_PAD_845 { get; set; }
        public DbSet<TS845> TS845 { get; set; }
        public DbSet<Loop_LIN_846> Loop_LIN_846 { get; set; }
        public DbSet<Loop_N1_846> Loop_N1_846 { get; set; }
        public DbSet<Loop_QTY_846> Loop_QTY_846 { get; set; }
        public DbSet<Loop_SLN_846> Loop_SLN_846 { get; set; }
        public DbSet<TS846> TS846 { get; set; }
        public DbSet<Loop_CON_849> Loop_CON_849 { get; set; }
        public DbSet<Loop_N1_849> Loop_N1_849 { get; set; }
        public DbSet<Loop_PAD_849> Loop_PAD_849 { get; set; }
        public DbSet<TS849> TS849 { get; set; }
        public DbSet<Loop_N1_850> Loop_N1_850 { get; set; }
        public DbSet<Loop_N9_850> Loop_N9_850 { get; set; }
        public DbSet<Loop_PID_850> Loop_PID_850 { get; set; }
        public DbSet<Loop_PO1_850> Loop_PO1_850 { get; set; }
        public DbSet<Loop_SLN_850> Loop_SLN_850 { get; set; }
        public DbSet<TS850> TS850 { get; set; }
        public DbSet<Loop_LIN_852> Loop_LIN_852 { get; set; }
        public DbSet<Loop_N1_852> Loop_N1_852 { get; set; }
        public DbSet<Loop_ZA_852> Loop_ZA_852 { get; set; }
        public DbSet<TS852> TS852 { get; set; }
        public DbSet<Loop_ACK_855> Loop_ACK_855 { get; set; }
        public DbSet<Loop_N1_855> Loop_N1_855 { get; set; }
        public DbSet<Loop_N9_855> Loop_N9_855 { get; set; }
        public DbSet<Loop_PID_855> Loop_PID_855 { get; set; }
        public DbSet<Loop_PO1_855> Loop_PO1_855 { get; set; }
        public DbSet<Loop_SLN_855> Loop_SLN_855 { get; set; }
        public DbSet<TS855> TS855 { get; set; }
        public DbSet<Loop_CLD_856> Loop_CLD_856 { get; set; }
        public DbSet<Loop_HL_856> Loop_HL_856 { get; set; }
        public DbSet<Loop_N1_856> Loop_N1_856 { get; set; }
        public DbSet<TS856> TS856 { get; set; }
        public DbSet<Loop_L0_858> Loop_L0_858 { get; set; }
        public DbSet<Loop_LH1_858> Loop_LH1_858 { get; set; }
        public DbSet<Loop_LX_858> Loop_LX_858 { get; set; }
        public DbSet<Loop_N1_858> Loop_N1_858 { get; set; }
        public DbSet<Loop_N7_858> Loop_N7_858 { get; set; }
        public DbSet<Loop_S5_858> Loop_S5_858 { get; set; }
        public DbSet<TS858> TS858 { get; set; }
        public DbSet<Loop_H1_859> Loop_H1_859 { get; set; }
        public DbSet<Loop_L0_859> Loop_L0_859 { get; set; }
        public DbSet<Loop_LS_859> Loop_LS_859 { get; set; }
        public DbSet<Loop_LX_859> Loop_LX_859 { get; set; }
        public DbSet<Loop_LX_859_2> Loop_LX_859_2 { get; set; }
        public DbSet<Loop_N1_859> Loop_N1_859 { get; set; }
        public DbSet<Loop_N7_859> Loop_N7_859 { get; set; }
        public DbSet<Loop_S5_859> Loop_S5_859 { get; set; }
        public DbSet<TS859> TS859 { get; set; }
        public DbSet<Loop_N1_860> Loop_N1_860 { get; set; }
        public DbSet<Loop_N9_860> Loop_N9_860 { get; set; }
        public DbSet<Loop_PID_860> Loop_PID_860 { get; set; }
        public DbSet<Loop_POC_860> Loop_POC_860 { get; set; }
        public DbSet<Loop_SLN_860> Loop_SLN_860 { get; set; }
        public DbSet<TS860> TS860 { get; set; }
        public DbSet<Loop_N1_861> Loop_N1_861 { get; set; }
        public DbSet<Loop_RCD_861> Loop_RCD_861 { get; set; }
        public DbSet<Loop_SLN_861> Loop_SLN_861 { get; set; }
        public DbSet<TS861> TS861 { get; set; }
        public DbSet<Loop_FST_862> Loop_FST_862 { get; set; }
        public DbSet<Loop_JIT_862> Loop_JIT_862 { get; set; }
        public DbSet<Loop_LIN_862> Loop_LIN_862 { get; set; }
        public DbSet<Loop_N1_862> Loop_N1_862 { get; set; }
        public DbSet<Loop_SHP_862> Loop_SHP_862 { get; set; }
        public DbSet<TS862> TS862 { get; set; }
        public DbSet<Loop_CID_863> Loop_CID_863 { get; set; }
        public DbSet<Loop_LIN_863> Loop_LIN_863 { get; set; }
        public DbSet<Loop_MEA_863> Loop_MEA_863 { get; set; }
        public DbSet<Loop_N1_863> Loop_N1_863 { get; set; }
        public DbSet<Loop_STA_863> Loop_STA_863 { get; set; }
        public DbSet<Loop_TMD_863> Loop_TMD_863 { get; set; }
        public DbSet<TS863> TS863 { get; set; }
        public DbSet<Loop_MIT_864> Loop_MIT_864 { get; set; }
        public DbSet<Loop_N1_864> Loop_N1_864 { get; set; }
        public DbSet<TS864> TS864 { get; set; }
        public DbSet<Loop_ACK_865> Loop_ACK_865 { get; set; }
        public DbSet<Loop_N1_865> Loop_N1_865 { get; set; }
        public DbSet<Loop_N9_865> Loop_N9_865 { get; set; }
        public DbSet<Loop_PID_865> Loop_PID_865 { get; set; }
        public DbSet<Loop_POC_865> Loop_POC_865 { get; set; }
        public DbSet<Loop_SLN_865> Loop_SLN_865 { get; set; }
        public DbSet<TS865> TS865 { get; set; }
        public DbSet<Loop_DTM_866> Loop_DTM_866 { get; set; }
        public DbSet<Loop_LIN_866> Loop_LIN_866 { get; set; }
        public DbSet<Loop_N1_866> Loop_N1_866 { get; set; }
        public DbSet<TS866> TS866 { get; set; }
        public DbSet<Loop_N1_867> Loop_N1_867 { get; set; }
        public DbSet<Loop_PTD_867> Loop_PTD_867 { get; set; }
        public DbSet<Loop_QTY_867> Loop_QTY_867 { get; set; }
        public DbSet<TS867> TS867 { get; set; }
        public DbSet<Loop_E10_868> Loop_E10_868 { get; set; }
        public DbSet<Loop_E12_868> Loop_E12_868 { get; set; }
        public DbSet<Loop_E20_868> Loop_E20_868 { get; set; }
        public DbSet<Loop_E24_868> Loop_E24_868 { get; set; }
        public DbSet<Loop_E30_868> Loop_E30_868 { get; set; }
        public DbSet<Loop_E34_868> Loop_E34_868 { get; set; }
        public DbSet<Loop_E40_868> Loop_E40_868 { get; set; }
        public DbSet<TS868> TS868 { get; set; }
        public DbSet<Loop_HL_869> Loop_HL_869 { get; set; }
        public DbSet<Loop_N1_869> Loop_N1_869 { get; set; }
        public DbSet<TS869> TS869 { get; set; }
        public DbSet<Loop_HL_870> Loop_HL_870 { get; set; }
        public DbSet<Loop_ISR_870> Loop_ISR_870 { get; set; }
        public DbSet<Loop_ISR_870_2> Loop_ISR_870_2 { get; set; }
        public DbSet<Loop_N1_870> Loop_N1_870 { get; set; }
        public DbSet<Loop_PO1_870> Loop_PO1_870 { get; set; }
        public DbSet<TS870> TS870 { get; set; }
        public DbSet<Loop_AK2_997> Loop_AK2_997 { get; set; }
        public DbSet<Loop_AK3_997> Loop_AK3_997 { get; set; }
        public DbSet<TS997> TS997 { get; set; }
    }
}
